### ISSUE TITLE
Bad RTSP Video/Audio Quality

### ISSUE THREAD

**Issue by bosscrew** [EliasKotlyar/Xiaomi-Dafang-Hacks#98] opened 2018-02-14 10:05 UTC
if i start any rtsp stream i got lagging video with poor video and audio quality. 
My Wifi Connection is good and my other xiofang is working with good video and audio at the same location.

**Comment by Pharizna** [comment] 2018-02-14 18:16
Duplicate of #83 ?

**Comment by iashwinprasada** [comment] 2018-02-14 22:14
can confirm, bad AV on latest commit. 
old binary works great. attaching for reference


[v4l2rtspserver-master.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/1725699/v4l2rtspserver-master.zip)

**Comment by EliasKotlyar** [comment] 2018-02-15 18:55
I changed the Bitrate from 2000 to 6000. Everything else is pretty "stock". I suppose that is the Problem. I will change it later.

**Comment by iashwinprasada** [comment] 2018-02-15 20:33
You had changed it to 5000, but I tried putting it back to 2000 but still seems to be the same. Something to do with the new sharedmem implementation?

**Comment by EliasKotlyar** [comment] 2018-02-16 12:18
The other feature which was implemented was:
OSD(now active all the time)
Semaphores(which will prevent this picture issues with single-image capture)

I assume that there maybe some issues with the semaphores...

**Comment by EliasKotlyar** [comment] 2018-02-17 00:35
Okey - i was able to find the error. I also tried to implement a new feature - setting the bitrate. But some API-Calls were missing, despite being in the documentation. I have replaced the SharedObject Libraries (Libimp.so) with the normal static compiled versions(.a). This had a huge impact on the quality of the stream. Its working pretty good - even on FULLHD. Also i was able to implement the feature. 
Now the setconf has another parameter:
setconf -k b -v 6000
will set the bitrate instantly to 6000 kbps.

**Comment by shinebar1001** [comment] 2018-02-18 14:45
Thank you, @EliasKotlyar, the quality is great! Are there any limits? When I change the bitrate to 2000 it sticks around 3 MBit, when I change it to 10kbit (absurd, I know) it goes down to an average of 1,4 MBit? In my opionion, 6 Mbit is perfect, but I just came to play around with the values.

**Comment by EliasKotlyar** [comment] 2018-02-18 15:27
Hello @shinebar1001 ,

I havent seen any limits - but i havent installed any error reporting when changing the bitrate. There is a bottleneck due to the audio-transmission which is for now in PCM-Format. I suppose its consuming a lot of bandwidth. It needs to be changed to MP3 or AAC, but this involves converting the PCM-Stream and compiling more libraries.

How do you measure this values? Is there any plugin for VLC?

**Comment by shinebar1001** [comment] 2018-02-18 18:39
Hi @EliasKotlyar okay, thank you. I measured the value with the Media-Information of VLC, but obviously it shows only the actual combined bitrate and is misleading, especially if audio is pcm.
But : no worry, 6Mbit with sound and a crisp fast image is great IMHO

**Comment by jmtatsch** [comment] 2018-02-18 18:56
Awesome, with `setconf -k b -v 6000` audio stutters much less if there is movement in the scene.

**Comment by MasterPIC** [comment] 2018-02-20 10:43
@EliasKotlyar I'd suggest to pass the parameters **-A 8000 -C 1** to v4l2rtspserver-master to have mono audio at 8000 Hz.

**Comment by iashwinprasada** [comment] 2018-02-20 10:59
But I think it makes sense to move to AAC audio first for stable performance. Also I think the microphone driver could be optimised, it has a lot of buzzing and and loud noise turns into crackle

**Comment by msj33** [comment] 2018-02-20 15:21
@iashwinprasada: I can confirm that noise hissing and cracks in the sound when updating to current Master - I'm not interested in the compressing/encoding, just more a use full sound recording when needed.

Another option for the status page could be to enable/disable the mic.

**Comment by Shaktohh** [comment] 2018-02-20 15:56
Is there a parameter to only get the audio stream ?

**Comment by fia5000** [comment] 2018-02-25 01:47
I can confirm that the audio quality is extremely poor. `setconf -k b -v 6000` didn't really help at all with the audio quality of the rtsp stream

**Comment by EliasKotlyar** [comment] 2018-02-25 13:28
I have updated the RTSP-Stream to support MP3. Can someone please test?
Also there is a toggle to deactivate audio. Just pass "-a" to v4l2master to disable Audio.

**Comment by shinebar1001** [comment] 2018-02-25 14:38
Sounds great! @EliasKotlyar can you please upload the new version? I'd like to test the new feature :)

**Comment by EliasKotlyar** [comment] 2018-02-25 15:02
Sorry, i have forgotten to push it. Now its pushed.

**Comment by shinebar1001** [comment] 2018-02-25 18:09
Works like a charm! The bitrate decreased massively and the quality of the sounds seems to be a little bit better (I suppose that this is an illusion :))

**Comment by iashwinprasada** [comment] 2018-02-26 18:25
Works great now! can confirm

**Comment by wojtulab** [comment] 2018-02-26 20:45
Is it working via tinycam? I've tried with error : 'there is no sound'

**Comment by kszere** [comment] 2018-02-27 08:14
Current Software not support audio in tinyCam.

**Comment by mattzuba** [comment] 2018-02-28 22:58
The MP3 encoding is great!  Brought down CPU usage in ffmpeg while copying to disk a ton.  Video is still an issue for me though.  The bottom 1/6th of the image or so continually distorts on and off while streaming.  I'm running at 15fps and a bit rate of 1000.  I also applied the modified uboot image to help with memory use to no avail.

**Comment by EliasKotlyar** [comment] 2018-02-28 23:31
@mattzuba You should increase the bitrate. 1000 seems really a small amount. Refer to here as a reference:
https://support.ustream.tv/hc/en-us/articles/207852117-Internet-connection-and-recommended-encoding-settings

**Comment by mattzuba** [comment] 2018-03-01 00:09
I tried with 2500, 4500 and 6000 and the same thing happens with all of those rates as well.  For 720p@15FPS, 1000 bps should be enough though.

**Comment by mattzuba** [comment] 2018-03-10 19:00
Hi @EliasKotlyar - I played with this a little more today, and I found that the higher the bit rate I go, the more distortion in the image I get.  At 6000, the bottom half (literally half, so around 360 pixels in height) of the image is distorted.  At 2000, it's about the bottom 1/5, and at 500, I have no distortion (but of course the picture quality looks like crap).  Strangely, if I bump the resolution up to 1920x1080 and run at 1500 bps, it works without distortion.  Any more bps and I start getting it.  But 1920x1080 also crops some of the image (why is that?).

I'm pretty sure this is not a network latency issue (unlikely, my Unifi AP shows a 99% signal quality with a 72Mb connection; camera is 15ft away, direct line of sight to AP), so I'm not sure what could be causing it.  Maybe my findings might help narrow down if it's something in the v4l binary.

**Comment by shinebar1001** [comment] 2018-03-10 19:16
I've got nearly the setup (Unifi AP AC LR) and had these problems too - my problem was a absolutely crowded channel with a lot of noise. I switched the wifi channel and everything went smooth again.

**Comment by mattzuba** [comment] 2018-03-10 21:56
I did an RF Scan from the AP and I was already on the channel with the least interference (1).  For grins, I switched to 6 because it seemed equally as low on noise and the problem persists on that channel as well. :(  It was worth a shot.

**Comment by msj33** [comment] 2018-03-13 23:09
Can also verify this issue - Have terrible distortions after upgrade......bottom half just get "washed out" once in a while.

Quite annoying.

Running default configuration here in VLC+HASS

Please post your optimal resolution+bitrate to it , thx

**Comment by tthk** [comment] 2018-04-01 09:12
I get horrible rtsp streams as well.  This setting in controlscripts/rtsp-h264 is the best, but only barely acceptable:
```
/system/sdcard/bin/busybox nohup /system/sdcard/bin/v4l2rtspserver-master -S -W 960 -H540
```

**Comment by Polv89** [comment] 2018-04-05 18:59
In which file we can edit audio configuration?
Thanks

**Comment by jmtatsch** [comment] 2018-05-10 05:48
@Polv89 look at #329

**Comment by jmtatsch** [comment] 2018-06-05 01:45
Now there is fine grained control options for both video and audio in 9b017cded2409718974712abe95dbc15930b8df1. Please reopen if still an issue.

**Closed by jmtatsch** 2018-06-05 01:45 UTC
