### ISSUE TITLE
dafang move left/right can not work

### ISSUE THREAD

**Issue by ioldfish** [EliasKotlyar/Xiaomi-Dafang-Hacks#370] opened 2018-05-20 02:55 UTC
Does this hack support move left/right/up/down，home assistant can not do it well，no any error logs...

**Comment by ioldfish** [comment] 2018-05-20 02:56
<img width="339" alt="2018-05-20 10 50 56" src="https://user-images.githubusercontent.com/2900244/40275220-6049ed6a-5c1c-11e8-8a9a-383d4acf7a59.png">

**Comment by jmtatsch** [comment] 2018-05-20 05:26
Duplicate of #288

**Closed by jmtatsch** 2018-05-20 05:26 UTC
