### ISSUE TITLE
Home-Assistant Beta 2021.6 Error

### ISSUE THREAD

**Issue by Wibias** [EliasKotlyar/Xiaomi-Dafang-Hacks#1738] opened 2021-05-27 17:15 UTC
Hey! On the newest upcoming Home-Assistant you get this Error.

```
Exception in async_discover when dispatching 'mqtt_discovery_new_cover_mqtt': ({'name': 'Haustuer Move Up/Down', 'unique_id': '****-move-up-down', 'device': {'identifiers': '****', 'connections': [['mac', '****']], 'manufacturer': 'Xiaomi', 'model': 'Dafang', 'name': 'Haustuer', 'sw_version': 'null - beta - null'}, 'set_position_topic': 'myhome/Haustuer/motors/vertical/set', 'position_topic': 'myhome/Haustuer/motors/vertical', 'command_topic': 'myhome/Haustuer/motors/vertical/set', 'payload_close': 'down', 'payload_open': 'up', 'optimistic': 'false', 'value_template': '{{ ((value|int)/(700/100))|round }}', 'set_position_template': '{{ ((position|int)*(700/100))|round }}', 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/usr/src/homeassistant/homeassistant/components/mqtt/cover.py", line 118, in validate_options raise vol.Invalid( voluptuous.error.Invalid: 'value_template' must be set together with 'state_topic'. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 160, in async_discover config = schema(discovery_payload) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 341, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 337, in _exec v = func(v) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 276, in __call__ raise er.MultipleInvalid([e]) voluptuous.error.MultipleInvalid: 'value_template' must be set together with 'state_topic'.
Exception in async_discover when dispatching 'mqtt_discovery_new_cover_mqtt': ({'name': 'Haustuer Move Left/Right', 'unique_id': '****-move-left-right', 'device': {'identifiers': '****', 'connections': [['mac', '****']], 'manufacturer': 'Xiaomi', 'model': 'Dafang', 'name': 'Haustuer', 'sw_version': 'null - beta - null'}, 'set_position_topic': 'myhome/Haustuer/motors/horizontal/set', 'position_topic': 'myhome/Haustuer/motors/horizontal', 'command_topic': 'myhome/Haustuer/motors/horizontal/set', 'payload_close': 'right', 'payload_open': 'left', 'optimistic': 'false', 'value_template': '{{ ((value|int)/(2600/100))|round }}', 'set_position_template': '{{ ((position|int)*(2600/100))|round }}', 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/usr/src/homeassistant/homeassistant/components/mqtt/cover.py", line 118, in validate_options raise vol.Invalid( voluptuous.error.Invalid: 'value_template' must be set together with 'state_topic'. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 160, in async_discover config = schema(discovery_payload) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 341, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 337, in _exec v = func(v) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 276, in __call__ raise er.MultipleInvalid([e]) voluptuous.error.MultipleInvalid: 'value_template' must be set together with 'state_topic'.
Exception in async_discover when dispatching 'mqtt_discovery_new_cover_mqtt': ({'name': 'Balkon Move Up/Down', 'unique_id': '****-move-up-down', 'device': {'identifiers': '****', 'connections': [['mac', '****']], 'manufacturer': 'Xiaomi', 'model': 'Dafang', 'name': 'Balkon', 'sw_version': 'null - beta - null'}, 'set_position_topic': 'myhome/Balkon/motors/vertical/set', 'position_topic': 'myhome/Balkon/motors/vertical', 'command_topic': 'myhome/Balkon/motors/vertical/set', 'payload_close': 'down', 'payload_open': 'up', 'optimistic': 'false', 'value_template': '{{ ((value|int)/(700/100))|round }}', 'set_position_template': '{{ ((position|int)*(700/100))|round }}', 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/usr/src/homeassistant/homeassistant/components/mqtt/cover.py", line 118, in validate_options raise vol.Invalid( voluptuous.error.Invalid: 'value_template' must be set together with 'state_topic'. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 160, in async_discover config = schema(discovery_payload) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 341, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 337, in _exec v = func(v) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 276, in __call__ raise er.MultipleInvalid([e]) voluptuous.error.MultipleInvalid: 'value_template' must be set together with 'state_topic'.
Exception in async_discover when dispatching 'mqtt_discovery_new_cover_mqtt': ({'name': 'Balkon Move Left/Right', 'unique_id': '****-move-left-right', 'device': {'identifiers': '****', 'connections': [['mac', '****']], 'manufacturer': 'Xiaomi', 'model': 'Dafang', 'name': 'Balkon', 'sw_version': 'null - beta - null'}, 'set_position_topic': 'myhome/Balkon/motors/horizontal/set', 'position_topic': 'myhome/Balkon/motors/horizontal', 'command_topic': 'myhome/Balkon/motors/horizontal/set', 'payload_close': 'right', 'payload_open': 'left', 'optimistic': 'false', 'value_template': '{{ ((value|int)/(2600/100))|round }}', 'set_position_template': '{{ ((position|int)*(2600/100))|round }}', 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/usr/src/homeassistant/homeassistant/components/mqtt/cover.py", line 118, in validate_options raise vol.Invalid( voluptuous.error.Invalid: 'value_template' must be set together with 'state_topic'. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 160, in async_discover config = schema(discovery_payload) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 341, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 337, in _exec v = func(v) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 276, in __call__ raise er.MultipleInvalid([e]) voluptuous.error.MultipleInvalid: 'value_template' must be set together with 'state_topic'. 
```

I replaced my mac with "***".

**Comment by hugalafutro** [comment] 2021-06-01 05:32
The whole mqtt subsystem could use a rewrite or a facelift or w/e you wanna call it imho. Camera with dafang-hacks is the only mqtt device from 30 or so mqtt devices I use that incessantly spams the mosquitto server with opening and closing connection tens of thousands of times per day, consequently rendering the mqtt logs unusable as 99.99% of mosquitto log is dafang spam.

Not saying I'm an expert but if 29 things out of 30 are done certain way I tend to think the 29 are right not the 1.

**Comment by timstanley1985** [comment] 2021-06-01 05:44
I did have a quick look at this a few weeks ago but hit a dead end.  The problem is that the MQTT solution is just a bash script that runs on a loop every 30 seconds.  It publishes about 20 metrics one by one and connects individually for each one.

Ideally I would want to rewrite it in something like python but that is out of scope for this device.

I can think of two ways we might be able to simplify this. We could add a variable to the script for each metric and add an if statement so it only published if the mertic has changed.  The other better option I think to explore would be using json to publish a single payload for all metrics.  This would mean only one message every 30 seconds.

**Comment by jmtatsch** [comment] 2021-06-01 06:10
Someone has written a working c/c++
MQTT handler not too long ago but hasn't had time to clean up/open source his code. Maybe someone here wants to find him, remind him and/or start from there.

**Comment by Wibias** [comment] 2021-06-03 17:00
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1016

And @CaptainHook8

**Comment by flinkebernt** [comment] 2021-06-06 09:33
This is related to a breaking change in Home Assistant, [https://github.com/home-assistant/core/pull/46059](https://github.com/home-assistant/core/pull/46059 ) where state_topic is required when using value_template (as far as I understand).  

As a quick workaround you ssh into your camera and edit the /system/sdcard/scripts/mqtt-autodiscovery.sh file. Edit the section under "Motor up/down/left/right". The position doesn't seem to update correctly yet, but at least the camera can be controlled.

```
  # Motor up/down/left/right
  $MQTT_COMMAND "$AUTODISCOVERY_PREFIX/cover/$DEVICE_NAME/motor_up_down/config" ${MOSQUITTOPUBOPTS} ${MOSQUITTOOPTS} -r -m "{\"name\": \"$DEVICE_NAME move up/down\", \"unique_id\": \"$MAC_SIMPLE-move-up-down\", $DEVICE_INFO, \"set_position_topic\": \"$TOPIC/motors/vertical/set\",  \"state_topic\": \"$TOPIC/motors/vertical\", \"position_topic\": \"$TOPIC/motors/vertical\", \"command_topic\": \"$TOPIC/motors/vertical/set\", \"payload_close\": \"down\", \"payload_open\": \"up\", \"optimistic\": \"false\", \"value_template\": \"{{ ((value|int)/($MAX_Y/$STEP))|round }}\", \"set_position_template\": \"{{ ((position|int)*($MAX_Y/$STEP))|round }}\"}"
  $MQTT_COMMAND "$AUTODISCOVERY_PREFIX/cover/$DEVICE_NAME/motor_left_right/config" ${MOSQUITTOPUBOPTS} ${MOSQUITTOOPTS} -r -m "{\"name\": \"$DEVICE_NAME move left/right\", \"unique_id\": \"$MAC_SIMPLE-move-left-right\", $DEVICE_INFO, \"set_position_topic\": \"$TOPIC/motors/horizontal/set\", \"state_topic\": \"$TOPIC/motors/horizontal\", \"position_topic\": \"$TOPIC/motors/horizontal\", \"command_topic\": \"$TOPIC/motors/horizontal/set\", \"payload_close\": \"right\", \"payload_open\": \"left\", \"optimistic\": \"false\", \"value_template\": \"{{ ((value|int)/($MAX_X/$STEP))|round }}\", \"set_position_template\": \"{{ ((position|int)*($MAX_X/$STEP))|round }}\"}" 

```

**Comment by reefland** [comment] 2021-06-06 15:16
@flinkebernt - thank you, was just trying to track this down.  Trying it out.

**Comment by reefland** [comment] 2021-06-06 16:14
So before making manual changes, I upgraded cams to latest stable firmware and seems fix was already incorporated. 

```
grep -c value_template /system/sdcard/scripts/mqtt-autodiscovery.sh
0

grep -c position_template /system/sdcard/scripts/mqtt-autodiscovery.sh
2

grep position_template /system/sdcard/scripts/mqtt-autodiscovery.sh

  $MQTT_COMMAND "$AUTODISCOVERY_PREFIX/cover/$DEVICE_NAME/motor_up_down/config" ${MOSQUITTOPUBOPTS} ${MOSQUITTOOPTS} -r -m "{\"name\": \"$DEVICE_NAME move up/down\", \"unique_id\": \"$MAC_SIMPLE-move-up-down\", $DEVICE_INFO, \"set_position_topic\": \"$TOPIC/motors/vertical/set\", \"position_topic\": \"$TOPIC/motors/vertical\", \"command_topic\": \"$TOPIC/motors/vertical/set\", \"payload_close\": \"down\", \"payload_open\": \"up\", \"optimistic\": \"false\", \"position_template\": \"{{ ((value|int)/($MAX_Y/$STEP))|round }}\", \"set_position_template\": \"{{ ((position|int)*($MAX_Y/$STEP))|round }}\"}"
  $MQTT_COMMAND "$AUTODISCOVERY_PREFIX/cover/$DEVICE_NAME/motor_left_right/config" ${MOSQUITTOPUBOPTS} ${MOSQUITTOOPTS} -r -m "{\"name\": \"$DEVICE_NAME move left/right\", \"unique_id\": \"$MAC_SIMPLE-move-left-right\", $DEVICE_INFO, \"set_position_topic\": \"$TOPIC/motors/horizontal/set\", \"position_topic\": \"$TOPIC/motors/horizontal\", \"command_topic\": \"$TOPIC/motors/horizontal/set\", \"payload_close\": \"right\", \"payload_open\": \"left\", \"optimistic\": \"false\", \"position_template\": \"{{ ((value|int)/($MAX_X/$STEP))|round }}\", \"set_position_template\": \"{{ ((position|int)*($MAX_X/$STEP))|round }}\"}"
```

**Comment by flinkebernt** [comment] 2021-06-06 18:26
I can see that now @reefland. It was updated in march for Home Assistant 2021.3.x. it seems. Time to upgrade my firmware then.

**Closed** 2021-06-09 06:41 UTC
