### ISSUE TITLE
SW Night Mode only working if Page is open

### ISSUE THREAD

**Issue by BMOtheConsole** [EliasKotlyar/Xiaomi-Dafang-Hacks#1145] opened 2019-09-01 20:14 UTC
On my Dafang Pan/Tilt Auto Night Mode is not working correctly, it is working flawless if im in the SW Night Configuration Tab on my Camera, but as soon as i leave the Page the SW Night Mode is not working anymore and the Camera is Stuck in Whatever Mode it was last

**Comment by gerardoaguilar** [comment] 2019-09-04 23:51
I am also facing this issue on my two Wyze V2 cameras.

**Comment by saipsa** [comment] 2019-09-05 15:01
the process is being killed it seems. see what process is started when the page is opened and add it to chron job for every 15 minutes.

**Comment by danmed** [comment] 2019-09-21 18:52
Also got this problem.. any actual solutions?

**Comment by dixnor** [comment] 2019-10-14 12:36
The only way I found and seems rock solid is to move the /system/sdcard/www/sw_night_configure.html to another location after you had configured the sensor thresholds.
This just to make sure that you never go back again to nightmode software configuration.
It seems that this html page interfers with autonightmode process in a certain way after you hit the page. Probably because it locks the process when reading the light sensor values.
Give it a try, works

**Comment by mbaruzzo** [comment] 2019-10-20 19:05
I have a dafang camera and experiencing the same issue, tried dixnor method but no luck. 
Not sure what else to try...

**Comment by davidpesce** [comment] 2019-10-25 00:32
Same issue here.

**Comment by msmarks** [comment] 2019-10-25 03:07
I run /system/sdcard/controlscripts/auto-night-detection in ssh, then it works, i don‘t know why.

**Comment by TRSx80** [comment] 2019-10-26 14:32
> I run /system/sdcard/controlscripts/auto-night-detection in ssh, then it works, i don‘t know why.

I did this method and it works.

That seems to be a script that (with no options supplied (it can also do some other things)) checks if auto-night-detection is already running, and if not, starts it. It also looks in a `CONF_FILE` which by default is `/system/sdcard/config/autonight.conf` and in my case contains:
`-S -j 3 -w 3 -1 1200000 -2 930000,14,10 -3 3000,17,8`.

Those settings look pretty familiar. I think that once you tweak them in the SW detection web page, you press the save button on that page, and it dumps them to this file. Then they can be invoked this way.

Only question remaining is, do we execute this just once each time the camera starts, or periodically with a cron job to check the conditions? I guess I will find out when it gets dark whether it adjusts automatically or not...

**Comment by vdwkes** [comment] 2019-10-27 19:21
Is there a possibility that auto night detection is always on , on startup of the camera?
I use a xiaofang with the dafang hack as a babycam. But everytime i plug it in i have to set the autonight mode on. As long as the cam is connected to power it works fine.

**Comment by TRSx80** [comment] 2019-10-30 01:46
I tried running /system/sdcard/controlscripts/auto-night-detection once, but that didn't get it working. So I ended up setting it up to run as a cron job every 15 min (or whatever the lowest setting was in the preconfigured folders) and so far it seems to be working (switching day/night automatically).

**Comment by jmtatsch** [comment] 2019-11-01 17:05
auto-night-detection is by default started with the camera. If it is not running we should investigate why it died.

**Comment by vdwkes** [comment] 2019-11-01 17:27
everytime i plug in my xiaofang S1 i have to set auto night detect manually

**Comment by SirRedwind** [comment] 2019-12-23 15:18
I have the same issue, but only in 1 of my 4 cameras. The other 3 work fine. Could it be something corrupted on the original installation of the firmware which never got updated? Maybe a fresh install would do it? Any thoughts?
Or... As @jmtatsch mentioned, this is default started with the camera. How do we know if it's still running and/or how did it crash?

**Comment by cwiggs** [comment] 2020-01-06 16:18
I'm also having this issue.  I implemented the workaround @TRSx80 mentioned using a cron job.  However on my Wyze V2 running `crontab` did not work until I created `/var/spool/cron/crontabs`

So, if anyone else has this issue, this is how I created the cronjob:

```
mkdir -p /var/spool/cron/crontabs
cat '* * * * * /system/sdcard/controlscripts/auto-night-detection' > /var/spool/cron/crontabs
```

That should run every minute. You can also use `crontab -e` and manually enter in the cron setting if you like.

**Comment by cwiggs** [comment] 2020-01-07 16:05
Looking into this more and I found when I went to the "SW Night Configuration" page that the following error was showing up in `/var/log/lighttpd-cgi-stderr.log`:

`cat: can't open '/system/sdcard/config/autonight.conf': No such file or directory`

Looking into this more and I found this issue: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/845#issuecomment-449803369

In that comment they mention to do the following:
* Browse to "SW Night configuration" page
* Disable "Auto Night Detection" under "Camera Controls"
* Click "save" on the "SW Night Configuration" page, which creates the `/system/sdcard/config/autonight.conf` file.

I followed those steps and now SW night mode seems to work correctly.  I suspect the issue is simple that the `/system/sdcard/config/autonight.conf` file is missing.  In the future if someone has this issue, try and run this command and see if it fixes the issue:

`cat '-S -j 3 -w 3 -1 1200000 -2 930000,14,10 -3 3000,17,8' > /system/sdcard/config/autonight.conf`

If the missing `autonight.conf` is really the issue I think the permanent fix is to include that file in the git repo so it will be there on a new install.

**Comment by danmed** [comment] 2020-01-07 16:28
I've just done your suggestions.. Previously my autonight.conf only contained "-S".. it now contains the parameters.. so will see what's what.

**Comment by cwiggs** [comment] 2020-01-07 16:42
@danmed I should have mentioned, I did reboot after I made my changes, perhaps that will help?

**Comment by davidpesce** [comment] 2020-01-07 17:14
> * Browse to "SW Night configuration" page
> * Disable "Auto Night Detection" under "Camera Controls"
> * Click "save" on the "SW Night Configuration" page, which creates the /system/sdcard/config/autonight.conf file.

This seemed to work for me as well. It created the autonight.conf file.

**Comment by danmed** [comment] 2020-01-07 17:15
Yeah i think the missing step is to re-enable auto night detection :)

**Comment by cwiggs** [comment] 2020-01-07 17:51
I created PR #1245 that adds the autonight.conf file.  Once that is merged we should be able to close this issue.

**Comment by Morphy99** [comment] 2020-02-11 21:32
I'm having this issue still. My autonight.conf existed and did contain -S but not the extra parameters. I added these but still it refuses to switch to night mode until the SW Night Configuration page is opened. I also copied autonight.conf.dist to autonight.conf (which contained the parameters).

It seems the SW Night Configuration page is only saving the file sw=-S.

**Comment by jmtatsch** [comment] 2020-02-12 08:10
Did you update with autoupdate?

**Comment by Morphy99** [comment] 2020-02-12 08:54
> Did you update with autoupdate?

Yea I updated last night and it still wasn't switching on without going to that page.

**Comment by Morphy99** [comment] 2020-02-17 22:43
Any suggestions how I can troubleshoot this? Is there a log for the night mode component?

**Comment by jmtatsch** [comment] 2020-02-17 22:57
Is it still not working? You do use a clean config file?

**Comment by Morphy99** [comment] 2020-02-17 23:27
I've tried deleting the autonight.conf file and stopping the service then
pressing Save on the config page. It generates the file ok but still
doesn't switch after a reboot. Service is showing as running.

**Comment by strikeir13** [comment] 2020-02-20 04:03
I'm also having this issue and I'm on the current firmware. My /var/log/lighttpd-cgi-stderr.log: has this error:
`/system/sdcard/www/cgi-bin/action.cgi: /system/sdcard/config/autonight.conf: line 3: -j: not found`

**Comment by jmtatsch** [comment] 2020-02-20 08:25
Can you post your autonight.conf?

**Comment by crackers8199** [comment] 2020-02-20 08:46
This is also not working for me...config file exists, service is running, but it's not switching. At all. Ever.

**Comment by jmtatsch** [comment] 2020-02-20 11:02
Can you look with what parameters the autonight executable is running? With ps?

**Comment by iceatcs** [comment] 2020-02-20 12:00
Ah, there is it.

I have a problem in here too with my Neos SmartCam (same shape as Xiaomi Xiaofang 1S and Wyzecam V2) 
I noticed that Xiaomi Dafang is working with no problem with HW and SW mode.

I assume Xiaofang 1S also have this problem as well. My mate said couldn't get it to work too.

**Comment by strikeir13** [comment] 2020-02-20 12:43
> 
> 
> Can you post your autonight.conf?

`autonight_mode=sw
hw_parameters=
sw_parameters=-S -j 3 -w 3 -1 1200000 -2 930000,14,10 -3 3000,17,8
# set ir_led_off to true in front of IR reflecting windows
ir_led_off=false
`

**Comment by jmtatsch** [comment] 2020-02-20 13:30
Ahh, the service is being called with the contents of the whole config file, this cannot work.

**Closed** 2020-02-20 13:49 UTC

**Comment by crackers8199** [comment] 2020-02-24 03:22
i just updated to latest version and it still doesn't seem to work. it's still running with the whole config file as options for the autonight script...

**Comment by iceatcs** [comment] 2020-02-24 03:42
The GUI update setting page is not for updating the mod (I assume it is for camera firmware if you put the file in the SD.

I always update by:
Backup your wpa_config/wpa_supplicant.conf
Remove all files from the microSD card
Put everything from "firmware_mod" folder into the root of the microSD card
Copy the backed up wpa_supplicant.conf from step 1 back into the config folder

You will have to re-setting.

**Comment by crackers8199** [comment] 2020-02-24 03:44
> The GUI update setting page is not for updating the mod (I assume it is for camera firmware if you put the file in the SD.
> 
> I always update by:
> Backup your wpa_config/wpa_supplicant.conf
> Remove all files from the microSD card
> Put everything from "firmware_mod" folder into the root of the microSD card
> Copy the backed up wpa_supplicant.conf from step 1 back into the config folder
> 
> You will have to re-setting.

can i do this via SSH while the cam is running? if i have to run around to every single camera and pull the SD card and do this every time i want to update that's going to get old real fast...

**Comment by iceatcs** [comment] 2020-02-24 03:53
I dunno if it will work while it running but it is what on [the installation page.](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md#updating-firmware)

I couldn't see any alternative in there.

If it is all work, I won't bother to update in any future.

**Comment by crackers8199** [comment] 2020-02-24 04:20
seems updating via FTP/SSH does work, even if it is a somewhat roundabout way to make it happen. here's what i did:

- git clone the repo
- mkdir /system/sdcard/update
- copy firmware_mod contents to this new update folder
- ssh into the cam
- run this command: cp -rp /system/sdcard/update/* /system/sdcard/.
- run this command: rm -rf /system/sdcard/update
- reboot camera

seems to have worked, the autonight script seems to be running now with the correct options.

**Comment by jmtatsch** [comment] 2020-02-24 06:18
@crackers8199 no updating shouldnt be broken, do you use a proxy or anything special?

**Comment by crackers8199** [comment] 2020-02-24 06:36
@jmtatsch yeah, i figured out what happened...i have my cameras restricted from talking to the internet. next time i need to update i'll turn that firewall rule off and i'm sure it'll work...but if anyone was interested, the steps i outlined above will work to update manually.

**Comment by throttlenerd** [comment] 2022-02-28 22:07
Hey guys! Updated firmware on Dafang and now I can't figure out how to turn off Auto Night Detection. I mean I see it in Settings but stopping this service does nothing. How can I make it always stay in Day Mode? When I navigate to Software Auto Night Settings the camera switches to Day Mode but then, if it's dark, switches to Night Mode. Is there any smart command line like "-S -j 3 -w 3 -1 1200000 -2 930000,14,10 -3 3000,17,8" I could use? Thank you!
