### ISSUE TITLE
tinyCam PTZ Support

### ISSUE THREAD

**Issue by SimoneBnc** [EliasKotlyar/Xiaomi-Dafang-Hacks#70] opened 2018-02-04 14:29 UTC
What are the best solutions to control the PTZ functions of the camera? I mean phone apps and also video surveillance / DVR. Controlling movements from web page is not very handy.

**Comment by EliasKotlyar** [comment] 2018-02-04 14:35
There is tinycam-support, which supports PTZ:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/41

**Comment by SimoneBnc** [comment] 2018-02-04 15:52
OK, but for a non phone perspective, is there any DVR supporting the PTZ?

**Comment by acittlau** [comment] 2018-02-04 16:15
@SimeBnc I'm using the PTZ from BlueIris. Set it the PZT as Generic HTTP and use commands /cgi-bin/action.cgi?cmd=motor_left etc.

**Comment by john3jo** [comment] 2018-02-05 01:54
The following script will work in iSpy, as long as you dont use a pssword to access the camera. 
Insert in the PTZ2 file by the bottom, right before </PTZSettings2>. 
At the moment I put these together, the original file had up to 249 cameras, hence the camera id 250 and 251. I added both IDs so the camera responds to both action.cgi and @kszere api.cgi in case you prefer one or the other:
[iSpy_PTZ.txt](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/1693589/iSpy_PTZ.txt)

**Comment by stantheboss** [comment] 2018-05-22 09:17
Flashed latest modded firmware yesterday, now ptz contols stopped working in tinycam. Has anything changed in the way ptz commands are sent lately?

**Comment by woody4165** [comment] 2018-05-23 19:47
Same here, no PTZ control over tinycam or other cam app in android.

**Comment by jmtatsch** [comment] 2018-05-23 19:49
Try to go a couple of releases back. I would try a893ce647eed0b6147ff794b0e6018abc1b05f08

**Comment by stantheboss** [comment] 2018-05-23 20:14
I don't want to go back, why can't the latest code be compatible with PTZ controls in TinyCam like it used to be?

**Comment by jmtatsch** [comment] 2018-05-24 03:07
In order to fix it, we first have to identify since which commit it doesn't work anymore.

**Comment by woody4165** [comment] 2018-05-24 06:14
just tried the [https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/commit/a893ce647eed0b6147ff794b0e6018abc1b05f08](url) and it's not working for me also in this version

**Comment by jmtatsch** [comment] 2018-05-24 06:17
Then go back further to this https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/commit/6b90ca89ca1fb69264ef4d5114dbb17fd19cc357

**Comment by woody4165** [comment] 2018-05-24 11:33
I went back to Apr. 25th and it's not working for me.
@stantheboss what version was working for you?
Maybe I have some issue on Android app configuration, I chose `RTSP over HTTP`
 and used `http://ipaddress:8554/unicast` as address

**Comment by stantheboss** [comment] 2018-05-24 15:05
I don't remember which version was that, but it's the one with the old UI and the first build that fixed an issue with the autonight detection not working...

**Comment by jmtatsch** [comment] 2018-05-25 03:17
Can you define root/ismart12 as basic auth user/pwd?
Accessing the cgi needs authentication since around that time.

**Comment by Dopeyr** [comment] 2018-05-25 09:03
I can confirm the latest works for me in tinycam, as long as I have the RTSP password set to the same as the HTTP password on the Dafang.

tinyCam only lets you set one user/password and they must be set the same on the Dafang for both RTSP + HTTP to work.

If the password is correct for RTSP, but not for HTTP, then you see the video stream, but see 'Command failed - 401 unauthorised' when using PTZ controls.

Perhaps a mod here could be to have a `.conf` file containing the password that we can read into the `v4l2rtspserver-master` options, *and* also set the HTTP password with it too? 

Currently lighttpd requires username to be root though, whereas v4l2rtspserver-master allows any user.

**Comment by stantheboss** [comment] 2018-05-25 16:45
OK, I need some clarification. Where do I set RTSP password within hacked firmware? The only thing I've changed after upgrading to the latest build is the http password. Did not touch the config on the TinyCam side and if I try to PTZ from TinyCam I get "Command Failed (400 - Unknown)" and I get that error even if I provide the root/<pwd> credentials in camera config in TinyCam.

**Comment by Dopeyr** [comment] 2018-05-25 19:09
@stantheboss Can I check you're using the `custom_vendors.xml` from https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/integration/tinycam/custom_vendors.xml ?

Might be worth checking the access logs on the dafang (Manage -> Logs - `/var/log/lighttpd-access.log`) When I use the left control I see the following, the very first time I do it:

```
x.x.x.x x.x.com:x - [25/May/2018:19:22:51 +0100] "GET /cgi-bin/action.cgi?cmd=motor_left HTTP/1.1" 401 351 "-" "Android/8.0.0 (Mi A1) com.alexvas.dvr.pro"
x.x.x.x x.x.com:x root [25/May/2018:19:22:52 +0100] "GET /cgi-bin/action.cgi?cmd=motor_left HTTP/1.1" 200 160 "-" "Android/8.0.0 (Mi A1) com.alexvas.dvr.pro"
```

The first is an unauthorised response, so tinycam tries again with user/pass, and gets a 200 response. You should see 400, but it would be good to see what you get.

For ref, I have changed the RTSP password by editing `rtspserver.conf` and setting `RTSPH264OPTS="-A -W1600 -H900 -F25 -U root:mypassword"` (-A disables audio, but doubt that's anything to do with it)

I have also set the http password on the dafang with: `http_password mypassword` and set user/pass to root/mypass in tinycam.

**Comment by hubmon** [comment] 2018-05-25 23:30
Dafang Hack is now supported in TinyCam v10.0.1 beta 2. No need for custom_vendor.xml anymore.

**Comment by woody4165** [comment] 2018-05-26 07:05
I've tried the fe3097b and also the 4601325 versions, but no luck for me. 
Can you tell the configuration you have in Tinycam for the dafang camera?
I've tried v10.0.1 (beta 2 and std version) and 9.0.1 Pro.
Thanks

**Comment by stantheboss** [comment] 2018-05-26 21:07
@Dopeyr what I did is:
- edited `/system/sdcard/config/rtspserver.conf`, so it start rtsp server with:
`RTSPH264OPTS="-W1280 -H720 -U root:<pwd>"`
- updated tinycam to latest beta, so it supports dafang hack out of the box now
- tiny cam rtsp stream is now secured with the password, 'cause server is started with the credentials as above
- PTZ within tinycam still does nothing but the error 400
- log `/var/log/lighttpd-access.log` contains:
```
192.168.xx.xxx - - [26/May/2018:22:56:56 +0200] "GET /cgi-bin/action.cgi?cmd=motor_right&val=100 HTTP/1.1" 400 349 "-" "Android/8.0.0 (LG-H930) com.alexvas.dvr.pro"
192.168.xx.xxx 192.168.xx.xxx root [26/May/2018:22:58:47 +0200] "GET /logs.html?_=1527368327128 HTTP/1.1" 200 2222 "http://192.168.99.110/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"
```
- manual http request as below fires PTZ just fine, so it's the tinycam seems to be lacking authorization somehow...
`dafang_ip/cgi-bin/action.cgi?cmd=motor_right&val=100`

**Comment by stantheboss** [comment] 2018-05-26 21:32
OK, it works, seems like a bug on my side at the first place :|
There is now need to force credentials usage for an rtsp stream, well at least it is not mandatory.
I do have a static dns enabled on my dd-wrt powered router and was accessing camera in tinycam using hostname rather than pure ip address - that was causing 400 error, same thing is happening while accessing web panel using a hostname.

I do not know why it behaves like this, previous build (match 29th) that I've used was resolving dns names just fine, or maybe it's the tinycam update that is messing around...

Sorry for a major mislead though...

**Comment by jmtatsch** [comment] 2018-05-27 17:49
@stantheboss in #380 there is a hostname issue as well. lets pinpoint when it stopped working and fix it.

**Comment by vheijnen** [comment] 2018-05-27 20:09
I think i might have the same issue with the dafangcam app (version 1.0.2.21052018.0). Connecting to the secured RTSP stream works but controlling the pan and tilt doesn't. Password and user combination for the RTSP stream and http server is the same.

When i put http://ip/cgi-bin/status.cgi address in the app i can see in the access log of httpd that it sends 301 (moved) responses to the app. The app responds with "Oups ;(" on the move commands.

When i put the https version of the adress in the app nothing happens in the access log. The app shows an "Oups, call cam error!" when trying to send a move command.

**Comment by jmtatsch** [comment] 2018-05-27 20:13
The control urls are redirected to https now for security reasons.
We need to edit custom_vendors.xml to reflect that.

**Comment by jmtatsch** [comment] 2018-06-08 01:46
Support for tinyCam is now well established.

**Closed by jmtatsch** 2018-06-08 01:46 UTC
Labels: tinyCam
