### ISSUE TITLE
Increased power consumption after using up, down and left movement

### ISSUE THREAD

**Issue by peturdainn** [EliasKotlyar/Xiaomi-Dafang-Hacks#249] opened 2018-04-19 15:05 UTC
As part of testing this for installation, I did some power consumption tests, and noticed something strange:
(movements done using live view web page arrow icons, consumption is *after* motion finished of course)

After boot, 3.8W
Press LEFT: 5.3W
Press RIGHT: back to 3.8W
Press UP: 6.8W
Press LEFT: 8.3W
Press DOWN: 6.8W
Press RIGHT: 5.3W

so different direction cause different extra consumption, and after using up or down the initial 3.8W is never possible any more (where the extra from LEFT is gone again after RIGHT)

I have not yet checked the code myself so I may update this issue if I find out more.

**Comment by peturdainn** [comment] 2018-04-19 16:11
Had a quick look in /drivers/misc/sample_motor/motor.c and after moving the gpios aren't switched off? 

Looks like it's doing microstep (8 steps), the driver should store its sequence in the steps but turn off all windings when target is reached. You don't want to power the windings to hold position.

But this doesn't explain why there is a difference between left/right/up/down :(

**Comment by hberntsen** [comment] 2018-04-24 17:14
Same issue here, running `/system/sdcard/bin/motor -d s` reduces the power usage to a normal level again which is between 1.8-2.2W in my case.

**Comment by peturdainn** [comment] 2018-04-29 21:59
@hberntsen if you want to test my fix for the motor power usage, I've attached the driver.
With this my idle current is always below 2W

[sample_motor.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/1959276/sample_motor.zip)

**Comment by peturdainn** [comment] 2018-04-29 22:39
There seems to be an identical issue with the IR cut filter. I think the gpio only needs activating to switch.
Sadly the state of the gpio is used for status

**Comment by peturdainn** [comment] 2018-04-30 19:57
@EliasKotlyar the IR Cut status is using the gpio to report on/off, and I want to disable both gpio after switching.

What would be an acceptable way to store the state for you? A file on /tmp?

**Comment by hberntsen** [comment] 2018-05-01 16:35
@peturdainn Just tested your driver, can confirm it works! Power usage drops back to normal indeed. I also have the issue with the IR cut filter. After booting I see a power usage of 1.15W, after changing the IR cut status it is 1.40W.

**Comment by peturdainn** [comment] 2018-05-01 16:44
great, thanks for confirming!

I'm now beginning to fear that the reports about broken camera's (too much power draw, etc) are related to the gpio of motor and ircut staying on. This extra current draw is not healthy.

**Comment by peturdainn** [comment] 2018-05-01 20:01
I created a PR that fixes the increased consumption due to IRcut switching, #325

**Comment by peturdainn** [comment] 2018-05-01 20:36
@hberntsen have you seen it happen that the camera has a higher current draw at boot? Just seen it, and initiating a motor movement fixes it.

Checked the driver and the gpio are not set to a value at start. If these are random this could be really bad (and really explain some people have a broken cam)

**Comment by peturdainn** [comment] 2018-05-01 20:57
Seen it again after adding a fix for it in the motor driver, looks like the extra current goes away doing any command, so not related to the motor.

**Comment by hberntsen** [comment] 2018-05-02 19:57
I just installed your fix for the ircut, that works. I've disabled autorun on all the services in the Manage -> Services page in the web interface. Power usage is now 2.27W after boot (constant). I cannot reduce this by toggling one of the 3 LEDs, toggling IR cut, moving the camera motor up/down. Once I rotate the camera to the left or the right, power usage drops to a constant 0.99W. This looks like an issue with the motor driver to me.

After a few (hard) reboots I've seen the power usage drop to a constant 0.74-0.79W. I don't know why it is lower now. I was able to reproduce the 2.27W like 3 times in a row or so. After plugging it in into another power supply I got 2.02W after boot again. Doing nothing except for unplugging and plugging it back in again and it's back to 0.79W. I can't reliably reproduce that high power usage.

**Comment by peturdainn** [comment] 2018-05-02 22:04
You're sharing my experiences ;)

Yes, the power usage sometimes does weird things and it's not easy to pinpoint a cause. At some point the higher current draw went away switching the ircut, which is why I mentioned I gues it is not motor related. Could be some pin left floating.

Anyway, I'm adding a newer motor driver that properly initializes gpio at startup, but as I mentioned it doesn't fix it completely. If you want to try it, let me know if you think it's already better.

My experience with weird bugs is that they mostly end up being a combination of bugs, which causes the seemingly random behaviour.

[sample_motor2.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/1969045/sample_motor2.zip)

**Comment by Dopeyr** [comment] 2018-05-03 07:49
Out of interest, does this happen on the default firmware? And as a n00b in this area, how do you go about monitoring the power usage?

**Comment by peturdainn** [comment] 2018-05-03 07:51
You can use a good AC power meter, or one of those USB inline meters
Not sure what the original firmware does, I never ran it ;)

**Comment by hberntsen** [comment] 2018-05-03 08:11
@Dopeyr I also never tried the default firmware. For power usage I have a power meter labelled 'USB Detector', it has 2 output USB ports, voltage indication in red and amperage in blue. By pressing the button I can switch the screen to show power draw in watts.

**Comment by Dopeyr** [comment] 2018-05-03 12:07
Thanks @peturdainn and @hberntsen. I've ordered an inline one to have a play with.

**Comment by Dopeyr** [comment] 2018-05-04 10:49
Been having a play, *without* the new changes in the pull request. It's very odd! 

On first try, I was seeing just over 3W. Move the camera left a couple of times and saw 4W, moved it back and it dropped to 3W. A couple of reboots later (usb cable out/in) I was seeing the same.

Then, on my 3rd or 4th go, I see just over 2W after boot. And now it seems to stick at that. 

I can't see a pattern to it either. However, the energy figures you have posted are much lower than I see, so the new code must be doing some good :)

**Comment by peturdainn** [comment] 2018-05-04 11:04
If you want to try, I have included the compiled motor driver in the zip a few posts above, just copy it into the /driver folder (you can rename the existing one as backup)

The ircut fix, I could zip it too if you want.

**Comment by SamHead** [comment] 2018-05-11 22:51
Here are some power readings collected a month ago.

[Photos power.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/1997012/Photos.power.zip)

Sam

**Comment by peturdainn** [comment] 2018-05-11 23:30
@EliasKotlyar gentle reminder not to forget to actually build and include the changed motor driver ;)

**Comment by hubmon** [comment] 2018-05-12 02:46
@SamHead
Are the readings WITH or WITHOUT the Hacks?

**Comment by SamHead** [comment] 2018-05-12 16:15
@hubmon 
With the hacks 1 month ago.
Other observations:
A failed calibration cycle may leave the motor stuck at one limit.
Some of my 4 cameras fail to run the motors properly. This may be a result of timing jitter, overspeed on step rate or failed coil driver.
A single step command fails to increment the motor in 1/2 step mode. This mode should alternate between 1 and 2 coils active.

**Comment by Kaeltis** [comment] 2018-05-28 10:12
Any reason why the built version of the updated driver wasn't merged yet?
Maybe create a pull request @peturdainn so someone can just merge it.

**Comment by peturdainn** [comment] 2018-05-28 10:29
I don't have a problem doing a PR for the binary, but it is better that the binary gets build by a maintainer IMHO. I posted a zipped binary in the comments so those who need it can take it without installing the toolchain.
I've asked the maintainers a few times to update the binary in the release, can't do more than that.

**Comment by jmtatsch** [comment] 2018-05-28 13:33
Sorry, forgot all about that ... I will build it later tonight.
Just out of curiosity @peturdainn did you have you have a look at the new sdk at https://github.com/beihuijie/Ingenic-kernel/tree/master/Ingenic_drivers/misc ? There seems to be fresher motor module... are the changes worth it?

**Comment by peturdainn** [comment] 2018-05-28 13:38
I hadn't seen it, will take a look and post back

**Comment by jmtatsch** [comment] 2018-06-05 01:33
We seem to have moved back to xiaomis motor driver in https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/commit/64228e7b94a8bc99d1fa3025036bda49fb8bfbe9, can someone please reevaluate if the power consumption still goes back to normal?

**Comment by Kaeltis** [comment] 2018-06-07 09:34
Running the current commit c3f9b9d66c05758311fb2a7e2b0d8cf9e2be84dc everything seems to be working fine for me - standby power draw (even after moving the camera in all directions) is about 270mA, same as it was with @peturdainn's driver.

**Comment by jmtatsch** [comment] 2018-06-07 09:41
Cool thx

**Comment by EliasKotlyar** [comment] 2018-06-07 22:36
Hello peturdainn,

Unfortunately, there is no way we can actually change this behaviour. Let me explain:
These new Dafang does not detect the end-stops with our previous driver. We can try to investigate why they are behaving like that, but it seems a really hard task and was not solved until now. Instead, we got new driver sources(at least not as old as the previous), and are able to communicate with the original (stock) driver, which is only delivered in binary form. I dont know exactly how its detecting the endstops, but it seems that it is using some different technique to do so. Maybe other Pins? We dont know, and cannot proceed here until we get the original Sources. I suppose that it wont happen very fast - if ever. In my opinion: Sacrificing the optional functionality instead of the core functionality one - is not a bad deal at all.

Greatings
Elias

**Comment by peturdainn** [comment] 2018-06-08 06:47
If I see how the current calibration works, the answer is quite simple:

Move right for the max number of steps and store that as right position. So it will just hit the end and keep driving the stepper. Is there an overview of which models have which 'features'?

Because my Dafang has end stops and they worked in the previous driver. I would love to get to the same functionality again on my unit ;)

**Comment by jmtatsch** [comment] 2018-06-08 07:39
I think there is only the old and new dafang actively supported with and without endstops. There is also a wyzecam pan on the same platform. I don't know whether it is based on the old or new dafang.

I have just taken apart my new dafang camera and can now confirm that there are really no endstops whatsoever.

![img_2714](https://user-images.githubusercontent.com/3080674/41145126-5df54c7a-6aff-11e8-91ab-48572dd7e195.jpg)
![img_2711](https://user-images.githubusercontent.com/3080674/41145127-5e0f2cc6-6aff-11e8-8423-92ae6c68d970.jpg)
![img_2712](https://user-images.githubusercontent.com/3080674/41145128-5e28f822-6aff-11e8-86d5-55cf4a940344.jpg)
![img_2713](https://user-images.githubusercontent.com/3080674/41145129-5e42e99e-6aff-11e8-82dc-123d6330046d.jpg)

The good news is that the only thing that winds up is the usb power cord and it is plenty loose to take some spinning up.

So the new dafang firmware must integrate the commands sent to the stepper motor to keep track of its position and then impose software boundaries.

**Comment by jmtatsch** [comment] 2018-06-08 07:42
@peturdainn I think we should be able to find some feature to differentiate both dafang revisions and load the old motor driver accordingly. Or we should also be able to do the tracking thing in the motor driver ourselves and have a generic motor driver.

**Comment by peturdainn** [comment] 2018-06-08 07:48
OK thanks for that explanation, I didn't know there were two versions of the Dafang

If the pins used for the stop switches in the old HW are not connected, an obvious trick would be to run max steps like the new driver does, but monitor the pins and use them if a pulse comes in.

**Comment by jmtatsch** [comment] 2018-07-02 08:45
Original issue seems solved.

**Closed by jmtatsch** 2018-07-02 08:45 UTC
