### ISSUE TITLE
Run official Mi Home app on the custom firmware

### ISSUE THREAD

**Issue by whuang1965** [EliasKotlyar/Xiaomi-Dafang-Hacks#32] opened 2018-01-01 11:21 UTC
Hi Elias,

Is it possible for your CWF to coexist with the Mi Home official app?

I have a few Xiaomi Mijia 1080p IP cams running CWF from, https://github.com/Filipowicz251/mijia-1080P-hacks, and it works quite well, i.e., both Mi Home official app and other third party rtsp app can be used to view the camera at the same time.

Right now, after the run.sh has been run, the camera is grayed out in the Mi Home official app.

Thank you very much for your effort and time to make this CWF work.

Regards,
Wade

**Comment by EliasKotlyar** [comment] 2018-01-01 22:17
Hello @whuang1965 ,

You can start the original Software using the following command:
```
/system/init/app_init.sh &
```
I suppose there will be some issues running this because of the custom driver. But you can still try.

**Comment by whuang1965** [comment] 2018-01-02 02:49
Hi, Elias,

Thanks for the tip, I'll give it a try.

By the way, is there a way to sync with a NTP server to get correct date/time according the timezone where I am at?

Also, inject a water mark with date/time on rtsp stream would be nice.

Regards,
Wade

**Comment by fnxpt** [comment] 2018-01-02 14:02
I tried to use the command to init the original software but It didn't work... 
The last thing I was able to see was an output MOTOR_MOVE, but the camera didn't move at all.

**Comment by marlontojal** [comment] 2018-01-02 14:08
Sometimes the script finishes with **[test_UP] 01/sbin/ifconfig wlan0 down**
BTW I'm starting it manually using ssh and after the command, the connection is broken
packet_write_wait: Connection to 10.2.250.228 port 22: Broken pipe

**Comment by pplucky** [comment] 2018-01-03 16:13
If we want to install an official firmware after we install this custom firmware, can we still do it? If so, how will be able? Has anyone tried it?

**Comment by EliasKotlyar** [comment] 2018-01-03 21:53
@whuang1965 
@fnxpt 
@marlontojal 
I have integrated a button to launch the original software. Please update to latest version and give it a try

**Comment by EliasKotlyar** [comment] 2018-01-03 21:54
@pplucky : Yes, you still can. Just use the regular demo.bin to install the old "firmware". You can find it in this repository.

**Comment by marine1988** [comment] 2018-01-05 00:22
it´s working @EliasKotlyar but canot stream and use xiaomi software at same time!

**Comment by pplucky** [comment] 2018-01-12 09:19
@EliasKotlyar It didn't seem to have worked for me and my camera hostname was changed to 'Ingenic-uc1_1' after I clicked the button.

What I did:
- Clicked 'Stop' button to stop RSTP
- Clicked 'Start' button to start original Xiaomi Software

Still then, camera doesn't appear in Mi Home app, no matter what.

Is there anything else that may need to be done? 
@marine1988 Can you share your experience also?

Thanks in advance.

**Comment by EliasKotlyar** [comment] 2018-01-14 21:37
@marine1988 : That might be difficult to achieve. The original application is blocking a lot of resources, and they cannot be used in CFW.

@pplucky : Does it work when you remove the SDcard?

**Comment by pplucky** [comment] 2018-01-14 21:48
@EliasKotlyar Yes it does.

**Comment by snjoetw** [comment] 2018-01-25 20:59
I haven't tried (don't have usable SD card yet :( ) but just curious, can I have camera viewable in MiHome app with CFW and still able to get a snapshot from the camera?

What I wanna achieve is have the snapshot show up in HomeAssistant every 10 seconds and if needed I can use MiHome app to view the video. Is this possible?

**Comment by pplucky** [comment] 2018-01-25 23:08
I don't think so, because to be able to take the snapshot, it must be running the custom firmware.

Still then, I don't think it is possible to have it running in custom firmware and appearing in MiHome app at the same time.

**Comment by jmtatsch** [comment] 2018-11-25 17:35
@u0x01 This isn't supported anymore.You can always boot into original fw by removing the sd card.  Closing this to avoid confusion.

**Closed by jmtatsch** 2018-11-25 17:35 UTC

**Comment by EsEnZeT** [comment] 2018-12-14 19:17
@jmtatsch if it's not supported, maybe can you remove the button in GUI to start original software?

Thanks!

**Comment by jmtatsch** [comment] 2018-12-15 04:01
Should have been fixed a long time ago already. Maybe it’s a regression. Would gladly accept a pull request.
