### ISSUE TITLE
"NOK" rtsp-* v4l2rtspserver-master failed to AddSensor, nothing else running

### ISSUE THREAD

**Issue by bobobo1618** [EliasKotlyar/Xiaomi-Dafang-Hacks#223] opened 2018-04-11 18:59 UTC
I have a brand new camera with the replacement bootloader. Steps to reproduce:
- Pull latest Git (hash 253d779bf24070ab0e883079c2c7487f281eb83d) and write to SD card
- Modify wpa_supplicant.conf
- Boot
- Start rtsp-h264
- All is well
- Reboot
- Start rtsp-h264
- "OK"
- Refresh manage scripts page
- "NOK"
- SSH and run `v4l2rtspserver-master`
   ```
   failed to AddSensor
   IMP_System_Init() failed
   Segmentation fault
   ```

**Comment by bobobo1618** [comment] 2018-04-11 19:25
I thought to look at dmesg and this looks highly relevant:

```
[   10.217594] request spk en gpio 63 ok!
[   10.219812] cgu_set_rate, parent = 860160000, rate = 2048000, n = 420, reg val = 0x000021a4
[   10.219830] i2s_global_init, i2s clk rate is 2048000
[   10.219842] cgu_enable,cgu_i2s reg val = 0x200021a4
[   10.706033] register all isp device successfully!
[   10.714343] @@@@ tx-isp-probe ok @@@@@
[   20.778346] set sensor gpio as PA-low-10bit
[   20.784857] probe ok ------->jxf22
[   20.810550] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
[   20.822072] i2c i2c-0: --I2C txabrt:
[   20.825793] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
[   20.841980] -----jxf22_detect: 426 ret = -5, v = 0x00
[   20.842000] jxf22 0-0040: chip found @ 0x40 (i2c0) is not an jxf22 chip.
[   20.864315] do_page_fault() #2: sending SIGSEGV to v4l2rtspserver- for invalid read access from
[   20.864315] 00000000 (epc == 004c2cf8, ra == 0045b454)
[  127.232315] i2c i2c-0: Failed to register i2c client jxf22 at 0x40 (-16)
[  127.239272] tx_isp: Failed to acquire subdev jxf22, deferring probe
[  127.248256] do_page_fault() #2: sending SIGSEGV to v4l2rtspserver- for invalid read access from
[  127.248256] 00000000 (epc == 004c2cf8, ra == 0045b454)
[  826.103870] i2c i2c-0: Failed to register i2c client jxf22 at 0x40 (-16)
[  826.110828] tx_isp: Failed to acquire subdev jxf22, deferring probe
[  826.119338] do_page_fault() #2: sending SIGSEGV to v4l2rtspserver- for invalid read access from
[  826.119338] 00000000 (epc == 004c2198, ra == 0045a884)
[  926.650241] i2c i2c-0: Failed to register i2c client jxf22 at 0x40 (-16)
[  926.657837] tx_isp: Failed to acquire subdev jxf22, deferring probe
[  926.666238] do_page_fault() #2: sending SIGSEGV to v4l2rtspserver- for invalid read access from
[  926.666238] 00000000 (epc == 004c21a8, ra == 0045a88c)
```

**Comment by EliasKotlyar** [comment] 2018-04-11 19:46
I suppose there is some error in the new binary. Try replacing the v4l2rtspserver-master binary with an older version.

**Comment by bobobo1618** [comment] 2018-04-11 19:48
I actually just booted it into original firmware and updated it (to 5.5.1.287) and it seems to be working again now. I'm not sure whether it's the running in official firmware or the update that did it though. I'll leave it a couple of days and see if it stays stable.

**Comment by bobobo1618** [comment] 2018-04-11 21:28
Unfortunately it didn't last long. 91 minutes of uptime, then nothing. RTSP connections start timing out, restarting the v4l2rtspserver shows OK but still times out.

dmesg shows:

```
82.363357] i2c i2c-0: --I2C txabrt:
[   82.367110] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
[   82.516139] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
[   82.523344] i2c i2c-0: --I2C txabrt:
[   82.527058] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
[ 5586.874618] free: 0, user: 8
[ 5586.877613] prepare-buffer underrun
[ 5589.452106] i2c i2c-0: Failed to register i2c client jxf22 at 0x40 (-16)
[ 5589.459073] tx_isp: Failed to acquire subdev jxf22, deferring probe
[ 5589.505085] do_page_fault() #2: sending SIGSEGV to v4l2rtspserver- for invalid read access from
[ 5589.505085] 00000000 (epc == 004c21a8, ra == 0045a88c)
[ 5741.574579] i2c i2c-0: Failed to register i2c client jxf22 at 0x40 (-16)
[ 5741.581548] tx_isp: Failed to acquire subdev jxf22, deferring probe
[ 5741.613580] do_page_fault() #2: sending SIGSEGV to v4l2rtspserver- for invalid read access from
[ 5741.613580] 00000000 (epc == 004c21a8, ra == 0045a88c)
```

Running the RTSP server manually displays

```
failed to AddSensor -1
IMP_System_Init() failed
```

Then hangs forever.

Restarting the device puts it back in the NOK state from earlier.

**Comment by bobobo1618** [comment] 2018-04-13 16:56
I tried pulling the v4l2rtspserver-master from 39d0058 and 62712d9 as well as building one from source and unfortunately no luck.

I'll also note I have two other cameras that are working fine, this problem seems to be isolated to this camera. I've tried switching SD cards with a working one but no luck. The other two cameras are on firmware 5.5.1.243 (which is what this one was on when this started).

**Comment by bobobo1618** [comment] 2018-04-15 15:14
I booted into Xiaomi firmware again and back but unfortunately that was no help. I tried copying drivers from the Xiaomi firmware to the modded firmware but also no help.

I am seeing this in dmesg on the latest firmware though:

```
[   27.014449] set sensor gpio as PA-low-10bit
[   27.018795] probe ok ------->jxf22
[   27.049144] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
[   27.061842] i2c i2c-0: --I2C txabrt:
[   27.068773] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
[   27.082001] -----jxf22_detect: 432 ret = -5, v = 0x00
[   27.082021] jxf22 0-0040: chip found @ 0x40 (i2c0) is not an jxf22 chip.
[   27.104113] do_page_fault() #2: sending SIGSEGV to v4l2rtspserver- for invalid read access from
[   27.104113] 00000000 (epc == 004c2cf8, ra == 0045b454)
```

Particularly interesting is the `jxf22 0-0040: chip found @ 0x40 (i2c0) is not an jxf22 chip.` line. Either there's something wrong with the drivers or I have a different sensor...?

**Comment by bobobo1618** [comment] 2018-04-15 15:28
And I didn't really do anything but it's suddenly working again... Here's a kernel log from when it's working:

```
[   10.348956] request spk en gpio 63 ok!
[   10.351179] cgu_set_rate, parent = 860160000, rate = 2048000, n = 420, reg val = 0x000021a4
[   10.351196] i2s_global_init, i2s clk rate is 2048000
[   10.351208] cgu_enable,cgu_i2s reg val = 0x200021a4
[   10.828434] register all isp device successfully!
[   10.835885] @@@@ tx-isp-probe ok @@@@@
[   13.011187] set sensor gpio as PA-low-10bit
[   13.017910] probe ok ------->jxf22
[   13.043835] -----jxf22_detect: 432 ret = 0, v = 0x0f
[   13.044335] -----jxf22_detect: 440 ret = 0, v = 0x22
[   13.044347] jxf22 0-0040: jxf22 chip found @ 0x40 (i2c0)
[   13.049853] tx_isp: Registered sensor subdevice jxf22 0-0040
[   13.055869] do not support ctrl->cmd ====1
[   13.055888] do not support ctrl->cmd ====0
[   13.065425] do not support ctrl->cmd ====1
[   13.592355] do not support ctrl->cmd ====1
[   13.592878] jxf22 stream on
[   13.643270] ###### image_tuning_v4l2_open 4219 #######
[   13.664480] &&& chan1  scaler.max_width = 1920 max_height = 1080  min_width = 128 min_height = 128 &&&
[   14.676627] dma dma0chan24: Channel 24 have been requested.(phy id 7,type 0x06 desc a5dfe000)
[   14.685578] ------ come to i2s_enable
[   14.690879] cgu_set_rate, parent = 860160000, rate = 11289600, n = 76, reg val = 0x2000204c
[   14.690899] i2s_set_rate, i2s clk rate is 11289600
[   14.690911] codec_codec_ctl: set sample rate...
[   14.690923] dp->filter convert_16bits_stereo2mono
[   14.696157] codec_codec_ctl: set device...
[   14.696173] codec_set_device 13
[   14.699516] codec_set_device: set device: MIC...
[   15.107085] i2s_set_rate, i2s clk rate is 11289600
[   15.107103] codec_codec_ctl: set sample rate...
```

**Comment by bobobo1618** [comment] 2018-04-15 15:43
Aaaand now I've caught it in the process of crashing:

```
[   13.654406] ###### image_tuning_v4l2_open 4219 #######
[   13.675333] &&& chan1  scaler.max_width = 1920 max_height = 1080  min_width = 128 min_height = 128 &&&
[   14.687423] dma dma0chan24: Channel 24 have been requested.(phy id 7,type 0x06 desc a5e05000)
[   14.696373] ------ come to i2s_enable
[   14.702031] cgu_set_rate, parent = 860160000, rate = 11289600, n = 76, reg val = 0x2000204c
[   14.702050] i2s_set_rate, i2s clk rate is 11289600
[   14.702061] codec_codec_ctl: set sample rate...
[   14.702073] dp->filter convert_16bits_stereo2mono
[   14.707211] codec_codec_ctl: set device...
[   14.707224] codec_set_device 13
[   14.710567] codec_set_device: set device: MIC...
[   15.117538] i2s_set_rate, i2s clk rate is 11289600
[   15.117556] codec_codec_ctl: set sample rate...
[   67.780099] ## VIC ERROR status = 0x00080000
[   92.687972] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
[   92.695173] i2c i2c-0: --I2C txabrt:
[   92.698917] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
[   92.705711] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
[   92.712861] i2c i2c-0: --I2C txabrt:
[   92.716580] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
[   92.723361] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
[   92.730495] i2c i2c-0: --I2C txabrt:
[   92.734219] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
[   92.767984] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
```

(And the lines repeat forever)

**Comment by bobobo1618** [comment] 2018-04-18 15:02
If it really is a hardware problem, I'm happy to mail mine to Munich or something so Elias can mess with it.

**Comment by mr-orange** [comment] 2018-05-02 10:05
I have the same issue reported on the first post.
However if I use an old version ( commit number 62712d932c6326f9dccea0e4c7ac19786304852e) I do not have any problem. Could you please reupload the correct version?

**Comment by bobobo1618** [comment] 2018-05-02 14:30
@mr-orange how long have you had it running on that version?

**Comment by mr-orange** [comment] 2018-05-04 09:17
Yesterday the v4l2rtsp-server crashed with the same dmesg error reported by bobobo1618.
Anyway Rebooting resolve the error.  Hope this can be fixed in short time.

**Comment by jmtatsch** [comment] 2018-05-14 05:15
@nik0 Could you please have a look at this?

**Comment by nik0** [comment] 2018-05-14 05:43
Can you post the logcat outputs, and also the server logs

**Comment by bobobo1618** [comment] 2018-05-14 07:05
Where can I find them? Isn't logcat an Android thing?

**Comment by nik0** [comment] 2018-05-14 07:06
You can have them in the log sections of the GUI or logcat is also a command. 
Yes it is also an Android stuff but the guys who developed the SDK reuse the same name

**Comment by moooff** [comment] 2018-05-14 07:53
Can you try a different resolution for the camera ? It also not works for me with 1920 x 1080 the maximal working resolution for me is 1600x900 (new camera from may).

When is start rtpserver with 1920x1080 i get the following errror message 
```
IMP_FrameSource_EnableChn(-1) error: 0
ImpStreamOn failed
```

**Comment by nik0** [comment] 2018-05-14 07:57
Did you do this https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/178#event-1559702675 ?

**Comment by SamHead** [comment] 2018-05-15 15:17
The problem is the image sensor connection (hardware)

   20.810550] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
[   20.822072] i2c i2c-0: --I2C txabrt:
[   20.825793] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK

**Comment by jmtatsch** [comment] 2018-07-02 08:47
Possible hardware issue. Please reopen if still an issue.

**Closed by jmtatsch** 2018-07-02 08:47 UTC

**Comment by Swiftnesses** [comment] 2018-12-13 06:56
I doubt this is a hardware issue, I get exactly the same issues on my camera (Xiaofang 1S 128MB).

**Comment by tiga31328** [comment] 2019-03-05 07:28
I just received my two v2 WZYE cameras today, having the same issue with both.  From reading the forms I see some older issues like what I am having, but they are all resolved (this is the closest, and most recently reported one so I am posting here).  After setting the wifi on the SD card, then loading it onto the cameras, I browse to them and there is an 'unable to load video' error, I also notice the NOK for RTSP, and RTSP will not stay started, starts and stops in a few seconds.  Based on the logs it appears that the video chip is not being recognized.  I tried two different SD Cards, formatted FAT32, and re-downloaded the current distro from GitHub and tried them again tonight.

Any assistance as to how to get around this is greatly appreciated, I was looking forward to outfitting the whole house with these cameras and using the RTSP streaming functionality to view them.

Logs below:

Summary:

Summary of all log files:

==> /var/log/boa.log <==
auth_check_userpass(dafang,ismart12,...);
192.168.52.34 - - [05/Mar/2019:07:20:58 +0000] "POST /cgi-bin/action.cgi?cmd=showlog HTTP/1.1" 200 1695 "http://192.168.52.31/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763"
auth_check_userpass(dafang,ismart12,...);
192.168.52.34 - - [05/Mar/2019:07:21:25 +0000] "POST /cgi-bin/action.cgi?cmd=showlog HTTP/1.1" 200 12299 "http://192.168.52.31/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763"
auth_check_userpass(dafang,ismart12,...);
192.168.52.34 - - [05/Mar/2019:07:26:08 +0000] "POST /cgi-bin/action.cgi?cmd=showlog HTTP/1.1" 200 145 "http://192.168.52.31/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763"
auth_check_userpass(dafang,ismart12,...);
cat: can't open '/tmp/v4l2rtspserver-master-h264.log': No such file or directory
192.168.52.34 - - [05/Mar/2019:07:26:24 +0000] "POST /cgi-bin/action.cgi?cmd=showlog HTTP/1.1" 200 61 "http://192.168.52.31/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763"
auth_check_userpass(dafang,ismart12,...);

==> /var/log/resolv.conf <==
nameserver 1.1.1.1 # wlan0
nameserver 192.168.52.1 # wlan0

==> /var/log/wpastat <==
1


Contents of dmesg

[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Initializing cgroup subsys cpuacct
[    0.000000] Linux version 3.10.14 (root@ubuntu) (gcc version 4.7.2 (Ingenic r2.3.3 2016.12) ) #21 PREEMPT Thu Oct 19 11:38:16 CST 2017
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU0 RESET ERROR PC:A786E1C0
[    0.000000] CPU0 revision is: 00d00101 (Ingenic Xburst)
[    0.000000] FPU revision is: 00b70000
[    0.000000] cgu_get_rate, parent = 860160000, rate = 0, m = 0, n = 0, reg val = 0x000020ff
[    0.000000] CCLK:860MHz L2CLK:430Mhz H0CLK:200MHz H2CLK:200Mhz PCLK:100Mhz
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 00535000 @ 00010000 (usable)
[    0.000000]  memory: 0003b000 @ 00545000 (usable after init)
[    0.000000] User-defined physical RAM map:
[    0.000000]  memory: 06800000 @ 00000000 (usable)
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x00000000-0x067fffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x00000000-0x067fffff]
[    0.000000] On node 0 totalpages: 26624
[    0.000000] free_area_init_node: node 0, pgdat 80541cb0, node_mem_map 81000000
[    0.000000]   Normal zone: 208 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 26624 pages, LIFO batch:7
[    0.000000] Primary instruction cache 32kB, 8-way, VIPT, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 8-way, VIPT, no aliases, linesize 32 bytes
[    0.000000] pls check processor_id[0x00d00101],sc_jz not support!
[    0.000000] MIPS secondary cache 128kB, 8-way, linesize 32 bytes.
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0 
[    0.000000] Built 1 zonelists in Zone order, mobility grouping off.  Total pages: 26416
[    0.000000] Kernel command line: console=ttyS1,115200n8 mem=104M@0x0 ispmem=8M@0x6800000 rmem=16M@0x7000000 init=/linuxrc rootfstype=squashfs root=/dev/mtdblock2 rw mtdparts=jz_sfc:256k(boot),2048k(kernel),3392k(root),640k(driver),4736k(appfs),2048k(backupk),640k(backupd),2048k(backupa),256k(config),256k(para),-(flag)
[    0.000000] PID hash table entries: 512 (order: -1, 2048 bytes)
[    0.000000] Dentry cache hash table entries: 16384 (order: 4, 65536 bytes)
[    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Memory: 99300k/106496k available (4024k kernel code, 7196k reserved, 1304k data, 236k init, 0k highmem)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] Preemptible hierarchical RCU implementation.
[    0.000000] NR_IRQS:418
[    0.000000] clockevents_config_and_register success.
[    0.000024] Calibrating delay loop... 858.52 BogoMIPS (lpj=4292608)
[    0.087753] pid_max: default: 32768 minimum: 301
[    0.092737] Mount-cache hash table entries: 512
[    0.097840] Initializing cgroup subsys debug
[    0.102101] Initializing cgroup subsys freezer
[    0.109175] regulator-dummy: no parameters
[    0.113466] NET: Registered protocol family 16
[    0.135468] bio: create slab  at 0
[    0.141793] jz-dma jz-dma: JZ SoC DMA initialized
[    0.147052] SCSI subsystem initialized
[    0.150983] usbcore: registered new interface driver usbfs
[    0.156558] usbcore: registered new interface driver hub
[    0.161991] usbcore: registered new device driver usb
[    0.167290] i2c-gpio i2c-gpio.1: using pins 57 (SDA) and 58 (SCL)
[    0.173499]  (null): set:249  hold:250 dev=100000000 h=500 l=500
[    0.179648] media: Linux media interface: v0.10
[    0.184201] Linux video capture interface: v2.00
[    0.191006] Switching to clocksource jz_clocksource
[    0.195962] cfg80211: Calling CRDA to update world regulatory domain
[    0.203038] jz-dwc2 jz-dwc2: cgu clk gate get error
[    0.207973] jz-dwc2 jz-dwc2: regulator vbus get error
[    0.213060] DWC IN OTG MODE
[    0.366312] sft id =========================off
[    0.370928] dwc2 dwc2: Keep PHY ON
[    0.374321] dwc2 dwc2: Using Buffer DMA mode
[    0.578466] dwc2 dwc2: Core Release: 3.00a
[    0.582588] dwc2 dwc2: DesignWare USB2.0 High-Speed Host Controller
[    0.588919] dwc2 dwc2: new USB bus registered, assigned bus number 1
[    0.596308] hub 1-0:1.0: USB hub found
[    0.600048] hub 1-0:1.0: 1 port detected
[    0.604207] dwc2 dwc2: DWC2 Host Initialized
[    0.608703] NET: Registered protocol family 2
[    0.613682] TCP established hash table entries: 1024 (order: 1, 8192 bytes)
[    0.620708] TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
[    0.627188] TCP: Hash tables configured (established 1024 bind 1024)
[    0.633641] TCP: reno registered
[    0.636839] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.642794] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.649395] NET: Registered protocol family 1
[    0.654112] RPC: Registered named UNIX socket transport module.
[    0.660044] RPC: Registered udp transport module.
[    0.664880] RPC: Registered tcp transport module.
[    0.669580] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.676623] freq_udelay_jiffys[0].max_num = 10
[    0.681050] cpufreq 	udelay 	loops_per_jiffy	
[    0.685516] dwc2 dwc2: ID PIN CHANGED!
[    0.689295] init DWC as A_HOST
[    0.692402] 12000	 59885	 59885	
[    0.695620] 24000	 119771	 119771	
[    0.699063] 60000	 299428	 299428	
[    0.702697] 120000	 598857	 598857	
[    0.706154] 200000	 998095	 998095	
[    0.709685] 300000	 1497142	 1497142	
[    0.713427] 600000	 2994285	 2994285	
[    0.717101] 792000	 3952457	 3952457	
[    0.720810] 1008000	 5030400	 5030400	
[    0.724619] 1200000	 5988571	 5988571	
[    0.734006] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.740849] jffs2: version 2.2. (NAND) © 2001-2006 Red Hat, Inc.
[    0.747451] msgmni has been set to 193
[    0.752690] io scheduler noop registered
[    0.756627] io scheduler cfq registered (default)
[    0.763302] jz-uart.1: ttyS1 at MMIO 0x10031000 (irq = 58) is a uart1
[    0.771492] console [ttyS1] enabled, bootconsole disabled
[    0.786711] brd: module loaded
[    0.791975] loop: module loaded
[    0.796255] zram: Created 2 device(s) ...
[    0.800491] logger: created 256K log 'log_main'
[    0.805901] jz SADC driver registeres over!
[    0.811215] jz TCU driver register completed
[    0.816307] the id code = 1c7018, the flash name is GD25LQ128C
[    0.822359] #####unsupport ID is 1c7018 if the id not be 0x00,the flash can be ok,but the quad mode may be not support!!!!! 
[    1.033896] JZ SFC Controller for SFC channel 0 driver register
[    1.040063] 11 cmdlinepart partitions found on MTD device jz_sfc
[    1.046305] Creating 11 MTD partitions on "jz_sfc":
[    1.051366] 0x000000000000-0x000000040000 : "boot"
[    1.056914] 0x000000040000-0x000000240000 : "kernel"
[    1.062636] 0x000000240000-0x000000590000 : "root"
[    1.068134] 0x000000590000-0x000000630000 : "driver"
[    1.073887] 0x000000630000-0x000000ad0000 : "appfs"
[    1.079480] 0x000000ad0000-0x000000cd0000 : "backupk"
[    1.085313] 0x000000cd0000-0x000000d70000 : "backupd"
[    1.091092] 0x000000d70000-0x000000f70000 : "backupa"
[    1.096937] 0x000000f70000-0x000000fb0000 : "config"
[    1.102735] 0x000000fb0000-0x000000ff0000 : "para"
[    1.108269] 0x000000ff0000-0x000001000000 : "flag"
[    1.113817] SPI NOR MTD LOAD OK
[    1.117145] tun: Universal TUN/TAP device driver, 1.6
[    1.122420] tun: (C) 1999-2004 Max Krasnyansky 
[    1.128963] usbcore: registered new interface driver zd1201
[    1.134815] usbcore: registered new interface driver r8152
[    1.140584] usbcore: registered new interface driver usb-storage
[    1.146958] usbcore: registered new interface driver usbserial
[    1.153075] usbcore: registered new interface driver usbserial_generic
[    1.159873] usbserial: USB Serial support registered for generic
[    1.166151] usbcore: registered new interface driver ch341
[    1.171880] usbserial: USB Serial support registered for ch341-uart
[    1.178431] usbcore: registered new interface driver cp210x
[    1.184253] usbserial: USB Serial support registered for cp210x
[    1.190427] usbcore: registered new interface driver pl2303
[    1.196251] usbserial: USB Serial support registered for pl2303
[    1.703439] i8042: i8042 controller selftest timeout
[    1.709065] wait stable.[246][cgu_msc0]
[    1.713106] jzmmc_v1.2 jzmmc_v1.2.0: vmmc regulator missing
[    1.752526] jzmmc_v1.2 jzmmc_v1.2.0: register success!
[    1.757916] jzmmc_v1.2 jzmmc_v1.2.1: vmmc regulator missing
[    1.795460] dwc2 dwc2:  ++OTG Interrupt: A-Device Timeout Change++
[    1.803447] jzmmc_v1.2 jzmmc_v1.2.1: register success!
[    1.808924] hidraw: raw HID events driver (C) Jiri Kosina
[    1.814808] usbcore: registered new interface driver usbhid
[    1.820584] usbhid: USB HID core driver
[    1.824669] Netfilter messages via NETLINK v0.30.
[    1.829600] nf_conntrack version 0.5.0 (1551 buckets, 6204 max)
[    1.836355] ip_tables: (C) 2000-2006 Netfilter Core Team
[    1.841972] TCP: cubic registered
[    1.845460] NET: Registered protocol family 17
[    1.851074] input: gpio-keys as /devices/platform/gpio-keys/input/input0
[    1.858314] drivers/rtc/hctosys.c: unable to open rtc device (rtc0)
[    1.870333] VFS: Mounted root (squashfs filesystem) readonly on device 31:2.
[    1.878140] Freeing unused kernel memory: 236K (80545000 - 80580000)
[    3.892410] jzmmc_v1.2 jzmmc_v1.2.0: card inserted, state=0
[    4.972012] wait stable.[246][cgu_msc0]
[    4.976071] mmc0: new high speed SDHC card at address 59b4
[    4.984447] mmcblk0: mmc0:59b4 00000 14.9 GiB 
[    4.992529]  mmcblk0: p1
[    6.881305] register all isp device successfully!
[    6.888762] @@@@ tx-isp-probe ok @@@@@
[    6.961890] exFAT: Version 1.2.9
[    6.973644] motor_probe743
[    7.011323] jz_codec_register: probe() successful!
[    7.018349] cgu_set_rate, parent = 860160000, rate = 2048000, n = 420, reg val = 0x000021a4
[    7.018367] cgu_enable,cgu_i2s reg val = 0x200021a4
[    7.362812] dma dma0chan24: Channel 24 have been requested.(phy id 7,type 0x06 desc a50b4000)
[    7.372070] dma dma0chan25: Channel 25 have been requested.(phy id 6,type 0x06 desc a4eed000)
[    7.398001] jz_pwm_probe[198] d_name = tcu_chn0
[    7.413018] request pwm channel 0 successfully
[    7.421970] pwm-jz pwm-jz: jz_pwm_probe register ok !
[    7.782508] RTL871X: module init start
[    7.786404] RTL871X: rtl8189ftv v4.3.24.7_21113.20170208.nova.1.02
[    7.794733] RTL871X: build time: Jan 24 2018 14:43:26
[    7.799981] wlan power on
[    7.822821] RTL871X: module init ret=0
[    7.868341] mmc1: card claims to support voltages below the defined range. These will be ignored.
[    7.901699] mmc1: new SDIO card at address 0001
[    7.918261] RTL871X: ++++++++rtw_drv_init: vendor=0x024c device=0xf179 class=0x07
[    7.979493] RTL871X: HW EFUSE
[    7.992480] RTL871X: hal_com_config_channel_plan chplan:0x20
[    8.182087] RTL871X: rtw_regsty_chk_target_tx_power_valid return _FALSE for band:0, path:0, rs:0, t:-1
[    8.212742] RTL871X: rtw_ndev_init(wlan0) if1 mac_addr=c8:02:8f:fd:49:33
[   11.299584] RTL871X: rtw_set_802_11_connect(wlan0)  fw_state=0x00000008
[   11.369078] RTL871X: start auth
[   13.817310] RTL871X: rtw_set_802_11_connect(wlan0)  fw_state=0x00000008
[   13.911148] RTL871X: start auth
[   13.917032] RTL871X: auth success, start assoc
[   13.925194] RTL871X: assoc success
[   14.928385] RTL871X: recv eapol packet
[   14.933322] RTL871X: send eapol packet
[   14.953363] RTL871X: recv eapol packet
[   14.957936] RTL871X: send eapol packet
[   14.964617] RTL871X: set pairwise key camid:4, addr:e0:3f:49:9a:88:f8, kid:0, type:AES
[   14.976344] RTL871X: set group key camid:5, addr:e0:3f:49:9a:88:f8, kid:2, type:TKIP
[   19.546723] set sensor gpio as PA-low-10bit
[   19.551074] probe ok ------->jxf22
[   19.579254] -----jxf22_detect: 432 ret = 0, v = 0x0f
[   19.579677] -----jxf22_detect: 440 ret = 0, v = 0x23
[   19.579692] jxf22 0-0040: chip found @ 0x40 (i2c0) is not an jxf22 chip.
[   19.598244] do_page_fault() #2: sending SIGSEGV to v4l2rtspserver- for invalid read access from
[   19.598244] 00000000 (epc == 004c2cf8, ra == 0045b454)


Contents of logcat

D/IMP-ISP (  213): ~~~~~~ IMP_ISP_Open[120] ~~~~~~~
E/IMP-ISP (  213): VIDIOC_REGISTER_SENSOR(jxf22) error!


Video Server:
Contents of v4l2rtspserver-master-h264.log

**Comment by nicktur100** [comment] 2020-03-22 22:29
I had the same error.  Was hardware error.  Opened up the camera and reseated the ribbon cable going to the camera (the widest one) and the issue is resolved.
