### ISSUE TITLE
AVM FRITZ!Fon live-picture

### ISSUE THREAD

**Issue by fanaticsurf** [EliasKotlyar/Xiaomi-Dafang-Hacks#422] opened 2018-06-06 21:32 UTC
Hi,
I need a picture size max 640x480 for use with a AVM FRITZ!Fon as live-picture

URL example:
http://192.168.178.25/bildverzeichnis/image.mjpeg
http://192.168.178.25/bildverzeichnis/image.jpg

currentpic.cgi does not work here and i did not find an option in jpegtran to manage it or an other tool to resize the image.
Can somebody help me or point me in the right direction?

Thanks
fanatic

**Comment by jmtatsch** [comment] 2018-06-08 01:46
Duplicate of #299

**Closed by jmtatsch** 2018-06-08 01:46 UTC
