### ISSUE TITLE
Wrong colors

### ISSUE THREAD

**Issue by helio58** [EliasKotlyar/Xiaomi-Dafang-Hacks#344] opened 2018-05-10 10:46 UTC
Hi my camera is a Dafang , haven't update the firmware for a while,
Today update , the video/pictures are not good, missing color , wrong color.
Did I miss same setting? 
The same with the ftp when log in cannot change the directory.

Thanks

**Comment by jmtatsch** [comment] 2018-05-10 11:25
H264 or mjpeg server? What resolution? Bitrate? What does your dmesg say?

**Comment by helio58** [comment] 2018-05-10 11:38
Using H264 , haven't make any changes just format sd card and copy the new firmware.
Need to use the camera, roll back to mars firmware. Will try again later and see what dmesg say.
Thanks

**Comment by Dopeyr** [comment] 2018-05-10 11:47
Could it be night mode/ir cut/ir led? Is it a purple colour or black and white? Might be worth playing with those switches to see if that helps.

**Comment by jmtatsch** [comment] 2018-05-10 12:58
As I thought a lot of memory underruns. Are you running any special services? Can you reduce the resolution? Can you show the output of the program free?

**Comment by helio58** [comment] 2018-05-10 13:38
No specials services just rtsp  no mqtt , I don't know how obtain the output of the program free. I don't know what program free. Sorry for that . Thanks

**Comment by helio58** [comment] 2018-05-10 14:14
Or how can i change the memory usage? If so how?
Thanks

**Comment by Kaeltis** [comment] 2018-05-10 17:32
I can confirm this color issue - it's caused by this commit: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/commit/3d50d0e0aac6356a8b4275376cfdafa5f78f88b4

When not mounting /root and /etc the color is ok, otherwise it's green. I'm guessing it needs some calibration thing from /etc that's missing after the mount?

**Comment by jmtatsch** [comment] 2018-05-10 17:37
@tssva do you have an idea what could be missing?

**Comment by Krysaenaar** [comment] 2018-05-10 17:40
Can also confirm the green/dark colour. I don't know what technical information to include, except i updated the mod files today with the latest

**Comment by Kaeltis** [comment] 2018-05-10 17:46
Created a PR, apparently it needs the stuff from /etc/sensor, copying the content since symlinks don't seem to work on FAT32

**Comment by jmtatsch** [comment] 2018-05-10 18:19
Fixed via #346. Please reopen if still an issue.

**Closed by jmtatsch** 2018-05-10 18:19 UTC
