### ISSUE TITLE
Xiomi Dafang motion tracking always goes to bottom left

### ISSUE THREAD

**Issue by CSmither** [EliasKotlyar/Xiaomi-Dafang-Hacks#652] opened 2018-08-22 20:49 UTC
Everything installed correctly no obvious errors in logs but only just installed today so not really sure what I am looking for.

The motion tracking seems to work in so far as it detects movement and moves the camera however the camera always moves to the bottom left, I can move it with the arrows on the web interface but it then returns back to the bottom left when I stop instructing it.

Resolution set to 1280
video format set to vbr
stream works fine

Any other info needed just ask :+1:

**Comment by akinomeroglu** [comment] 2018-08-27 09:48
Hey all,

I suffer from this bug too.

**Comment by nik0** [comment] 2018-08-27 13:03
Do you have some server logs? To see if the problem is on the detection side or on the moving script

**Comment by akinomeroglu** [comment] 2018-08-29 08:02
Hey @nik0 could you kindly tell me where the logs stored. I can share it tonight.

Thanks,

**Comment by nik0** [comment] 2018-08-29 08:07
On the web interface go to "informations/logs" and "video server" tab
You should have something like this:
`Will execute command /system/sdcard/scripts/detectionTracking.sh 1 0 0 0`

If you can ssh to the camera you can run theses commands:
`/system/sdcard/scripts/detectionTracking.sh 1 0 0 0`
`/system/sdcard/scripts/detectionTracking.sh 0 1 0 0`
`/system/sdcard/scripts/detectionTracking.sh 0 0 1 0`
`/system/sdcard/scripts/detectionTracking.sh 0 0 0 1`

**Comment by akinomeroglu** [comment] 2018-09-01 19:58
@nik0 hello again sir,

Sorry for delay. Please let me know if you need something else.

`[root@DAFANG:~]# /system/sdcard/scripts/detectionTracking.sh 1 0 0 0
1 0
0 0
Left move
x: 0
y: 0
speed: 900
Up move
x: 0
y: 100
speed: 900
[root@DAFANG:~]# /system/sdcard/scripts/detectionTracking.sh 0 1 0 0
0 1
0 0
Right move
x: 100
y: 100
speed: 900
Up move
x: 100
y: 200
speed: 900
[root@DAFANG:~]# /system/sdcard/scripts/detectionTracking.sh 0 0 1 0
0 0
1 0
Left move
x: 0
y: 0
speed: 900
Down move
x: 0
y: 0
speed: 900
[root@DAFANG:~]# /system/sdcard/scripts/detectionTracking.sh 0 0 0 1
0 0
0 1
Right move
x: 100
y: 0
speed: 900
Down move
x: 100
y: 0
speed: 900
[root@DAFANG:~]# 
`

**Comment by akinomeroglu** [comment] 2018-09-01 19:59
@nik0 Hello again sir,

Sorry for delay. Here are the logs

[root@DAFANG:~]# /system/sdcard/scripts/detectionTracking.sh 1 0 0 0
1 0
0 0
Left move
x: 0
y: 0
speed: 900
Up move
x: 0
y: 100
speed: 900
[root@DAFANG:~]# /system/sdcard/scripts/detectionTracking.sh 0 1 0 0
0 1
0 0
Right move
x: 100
y: 100
speed: 900
Up move
x: 100
y: 200
speed: 900
[root@DAFANG:~]# /system/sdcard/scripts/detectionTracking.sh 0 0 1 0
0 0
1 0
Left move
x: 0
y: 0
speed: 900
Down move
x: 0
y: 0
speed: 900
[root@DAFANG:~]# /system/sdcard/scripts/detectionTracking.sh 0 0 0 1
0 0
0 1
Right move
x: 100
y: 0
speed: 900
Down move
x: 100
y: 0
speed: 900
[root@DAFANG:~]# 

Please let me know if you need something else.

**Comment by nik0** [comment] 2018-09-01 20:26
Which one doesn't work ? I don't any "strange" things ...

**Comment by akinomeroglu** [comment] 2018-09-01 20:33
@nik0 I go to manage menu then motion detection page than turn on motion tracking after a second camera all goes to bottom left and never respond commands without a calibration

**Comment by nik0** [comment] 2018-09-01 20:48
And the commands you run in ssh ( /system/sdcard/scripts/detectionTracking.sh) does it react accordingly ?

**Comment by akinomeroglu** [comment] 2018-09-01 20:50
@nik0 if it is left, right, left and right yes it is react correctly.

**Comment by nik0** [comment] 2018-09-01 21:07
Did you activate "Motion Timeout", I mean there is something different than -1 ?

**Comment by nik0** [comment] 2018-09-02 07:12
Please update to the last version (autoupdate)
Post the server logs also 
I have to admit that I don't understand your problem ....

**Comment by jmtatsch** [comment] 2018-09-02 08:16
Do you have old or new dafang? Did you run calibration on startup?

**Comment by CSmither** [comment] 2018-09-02 13:36
In my logs I have for video Server
`2018-09-02 20:28:18.857 ( 630.844s) [ivsMoveDetection]         ImpEncoder.cpp:407      0| Execute /system/sdcard/scripts/detectionOff.sh returned:0
2018-09-02 20:28:19.296 ( 631.283s) [main thread     ]       DeviceSource.cpp:110      0| V4L2DeviceSource::doStopGettingFrames
2018-09-02 20:28:19.297 ( 631.283s) [main thread     ]       DeviceSource.cpp:110      0| V4L2DeviceSource::doStopGettingFrames
2018-09-02 20:28:19.297 ( 631.284s) [main thread     ]       DeviceSource.cpp:110      0| V4L2DeviceSource::doStopGettingFrames
2018-09-02 20:28:19.298 ( 631.284s) [main thread     ]       DeviceSource.cpp:110      0| V4L2DeviceSource::doStopGettingFrames
`
Running the commands you gave me produced the following
`[root@DAFANG:]# /system/sdcard/scripts/detectionTracking.sh 1 0 0 0
x: 0
y: 0
speed: 900
x: 0
y: 0
speed: 900
[root@DAFANG:]# /system/sdcard/scripts/detectionTracking.sh 0 1 0 0
x: 0
y: 0
speed: 900
x: 0
y: 0
speed: 900
[root@DAFANG:]# /system/sdcard/scripts/detectionTracking.sh 0 0 1 0
x: 0
y: 0
speed: 900
x: 0
y: 0
speed: 900
[root@DAFANG:]# /system/sdcard/scripts/detectionTracking.sh 0 0 0 1
x: 0
y: 0
speed: 900
x: 0
y: 0
speed: 900`

I run calibration on startup.
The buttons on the web interface to move the camera work but it then returns to the bottom left after a couple of seconds

**Comment by CSmither** [comment] 2018-09-02 14:30
Have done and seems to be better, Tracking is still slow but kinda works now, thanks.

Out of interest what script/service calls motionTracking.sh?

**Comment by nik0** [comment] 2018-09-02 14:33
This is the video server process who call this.
If it is too slow you can try to edit detectionTracking.sh and change the var STEPS

**Comment by CSmither** [comment] 2018-09-02 14:50
That's what I'm thinking. maybe a few other changes as well. Thanks for your help

**Comment by jmtatsch** [comment] 2018-09-02 18:11
Sure, just uncommercial the appropriate calibration in your run.sh

**Comment by akinomeroglu** [comment] 2018-09-05 07:48
@jmtatsch thanks for your help calibrating after power loss fixes my motion track problem. 

Unfortunately, Camera still goes bottom left if I enable return original position after ... seconds option. I could open a new issue if you want and close this issue if @CSmither agrees.

Thanks again,

**Comment by nik0** [comment] 2018-09-05 07:51
What values do you have in /tmp/cameraposition
This is where the "original" position is stored, may be it doesn't work (anymore)

**Comment by akinomeroglu** [comment] 2018-09-07 12:09
@nik0 aha! that's the problem. There is no file like /tmp/cameraposition and for this reason camera return to 0,0 I think. 

I changed the file a bit and now write it to sdcard and it is working now. I will test a little bit and open a pr if necessary.

**Comment by thylive** [comment] 2018-10-02 01:15
@akinomeroglu I have the same problem，can you tell me how to solve this ？

**Comment by SiliconAvatar** [comment] 2018-11-17 04:16
I resubmitted this as [issue #802](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/802) with some new information.

To fix this, temporarily, First you have to change "detectionTracking.sh". You can do this from reading the SDCard externally, or use VI inside SSH; comment out or delete lines 103,104, and 105. This will stop the camer from overwriting the home position. next, SSH into the camera, go to the /tmp/ directory, and run "touch cameraposition" this will create the file that holds the "home" position. Then edit it in VI and type in X: xxxx" and "Y: xxxx: where the 'xxxx' sections hold the coordinates you want the camera to return to. Add a line break between them so the file is 2 lines long, one has the X position and the other the Y. You can find the position you want it to return to by first running the calibration, then centering the camera where you want and either looking at the position on the OSD, or running "/system/sdcard/bin/motor -d s" in the camera SSD command prompt. 

Once you have "detectionTracking.sh" no longer overwriting the position, and have the position file created and entered in the home position, it should work fine. Until it's rebooted, then the tmp directory is deleted. If you want to make this persistent, change line 16 of "detectionTracking.sh" to somewhere inside "/system/sdcard" and create the file there which will hold the home position of the camera.

Hopefully this issue get's resolved the proper way though, so this isnt needed.

**Closed** 2019-05-26 16:28 UTC
Labels: wontfix
