### ISSUE TITLE
IR (night) vision

### ISSUE THREAD

**Issue by sharkoz** [EliasKotlyar/Xiaomi-Dafang-Hacks#9] opened 2017-12-06 22:20 UTC
Any way to switch to night vision ?

**Comment by D0m3L** [comment] 2017-12-06 22:44
Same question here - even if I run IR LED on (and can see e.g. from my phone camera that the leds are on) they in fact do not adequately illuminate the surroundings so the image remains black. Is there a way of controling IR LED power?

**Comment by sharkoz** [comment] 2017-12-06 22:53
I beleive it is not only the LED power but also a filter on the sensor (as I can hear a click when the cam switches to night vision with the original FW). I tried to play with the GPIO 77 which does not seem to be used yet but it was a long shot and it did nothing to the IR vision.

**Comment by deennoo** [comment] 2017-12-07 17:57
Same issue here with night vision

**Comment by EliasKotlyar** [comment] 2017-12-07 21:41
Hey, i included some patch for the jpeg-capture which will allow to use IR-Mode. Can someone test? Just update to latest firmware and modify the parameter in the URL to "nightvision=1"

**Comment by dbuxo** [comment] 2017-12-07 22:12
Parameter is not working for me, with light, nightvision=1 turns image to b/w.
Without light, its just as black as with the normal mode, turning on IR leds only shows some purple spots.

**Comment by dbuxo** [comment] 2017-12-07 22:13
Sample capture, without any light and nightvision=1

![image](https://user-images.githubusercontent.com/708781/33741326-1e3c87fa-dba4-11e7-9c25-bf3bcfaa928a.png)

**Comment by sharkoz** [comment] 2017-12-07 22:24
same here, image is in greyscale but not in IR.
Furthemore the setting is not consistent, and if I refresh several times with nightvision=1, it's in B/W only the first time, and then the next refreshes are back to color. I have to go once to nightvision=0 and then back to nightvision=1 to have it (only once) in B/W

**Comment by jbeck22** [comment] 2017-12-08 15:35
I can also confirm the above.  First time I see the pic in b/w, but even with nightvision=1 in the URL when I refresh it is back to color.

**Comment by EliasKotlyar** [comment] 2017-12-10 19:14
Hello everyone,

Many thanks for your Feedback. It was the only option in the camera which had something to do with the nightvision. I really have no clue for now how to resolve this issue. Do someone have a hint?  

The documentation for the camera-module can be found here:
https://github.com/dim08/Ingenic-T10_20/blob/master/doc.7z


Greatings
Elias

**Comment by MasterPIC** [comment] 2017-12-10 19:48
Hi,
I'm still waiting for an Dafang delivery. Anyway I hope to be of help...
On github I found some documentation about Ingenic dev boards... And it seems that AP1511A is present on some boards...
It's a filter switch driver. Maybe it's used by Dafang too...
The chip is properly documented online.

**Comment by MasterPIC** [comment] 2017-12-13 18:00
Did you give a look at the PCB? Maybe tracing the PCB tracks, starting from the IC used to drive the filter, you can figure out the GPIO pin required to properly move the filter...

**Comment by CliffordClavin** [comment] 2017-12-16 23:46
Hi,

I had a closer look at the PCBs. The PCB with the camera sensor has a BA6208G chip. According to it's datasheet it is a reversible motor driver. This IC drives a coil, which changes the filter (IR,  not IR) with a mechanical construction. The BA6208G has 8 Pins. VCC, GND, Ain, Bin, Aout and Bout. Aout and Bout a connected to the aforementioned coil. Ain and Bin can be traced to the big ribbon cable and from there to the PINs in the picture.

The Ingenic T20 is a BGA-Chip. Therefore I was not able to derive the exact pin of the T20. Maybe someone with more expierence in electronics can conclude it.
![Uploading IR-Filter-Pins.jpg

**Comment by MasterPIC** [comment] 2017-12-17 01:24
I think Ain=LOW & Bin=HIGH (Ain=HIGH & Bin=LOW) should be used to move (remove) the IR filter.
Then they should stay LOW...
But I've no idea how to derive the corresponding T20 pins.
Anyway I gave a look at bootlog.md taken by picocom:
gpio_request lable = night_gpio gpio = 81
gpio_request lable = night_gpio gpio = 25
gpio_request lable = night_gpio gpio = 49
Could they be related to the IR filter management?

**Comment by CliffordClavin** [comment] 2017-12-17 05:26
Do we know the pin for the IR-LEDs? If not, maybe one of them is responsible for the IR-LEDs and the two other are Ain and Bin. I think the the IR-LED pin has to provide a PWM signal. (As far as I remember the connector for the IR-LED PCB had something with PWM printed nearby.)

Is it possible to scan the original firmware code for the combination: PWM, one pin low, one pin high. Maybe even the code for one pin, one pin high is quite characteristic.

**Comment by EliasKotlyar** [comment] 2017-12-17 21:39
Okey, i got it - according to the documentation of the "Bull"-Board, the pins were 25 & 26. After enabling them and triggering around, i was able to get the IR-Cut to work. Can someone please have a test?

Here is the hardware documentation of the "Bull-Board":
https://github.com/dim08/Ingenic-T10_20/blob/master/hardware/RD_T20_BULL_V10_20160912B.pdf

**Comment by CliffordClavin** [comment] 2017-12-17 22:01
Cool, it works :-)

**Comment by WatermelonFox** [comment] 2017-12-17 22:54
I confirm too that it works great, I've got a rather puprle picture on rtsp but I guess we have to manage some pins to configure the IR filter!

**Comment by CliffordClavin** [comment] 2017-12-18 09:30
I can confirm the purple image, too. I never used the original firmware, so I don't know if it differs there. But most probably one has to switch to a grayscale image for the nightmode.

**Comment by D0m3L** [comment] 2017-12-18 09:38
That is right. Grayscale should do the trick.
Original firmware image with nightmode looks like:
![obraz](https://user-images.githubusercontent.com/23291471/34099358-9f26aa10-e3df-11e7-9503-4bf42b48b4fb.png)

**Comment by jbeck22** [comment] 2017-12-18 14:56
I too get the purple pic like others above.  Using the most updated CFW.

**Comment by EliasKotlyar** [comment] 2017-12-18 19:40
I have updated the binary of the "jpegSnap". It sholud now provide a B/W picture.

**Comment by sharkoz** [comment] 2017-12-18 19:46
It works great thanks ! Using http://IP/cgi-bin/currentpic.cgi?width=1920&height=1080&nightvision=1 I get a very good B/W IR image 👍

**Comment by dmolner** [comment] 2017-12-18 22:40
@CliffordClavin Could you make a photo to J10 component?
I think these component is for center the cam.
Is possible wires at right go to T20

**Comment by deennoo** [comment] 2017-12-19 08:10
Ok for my after enable IR led + Ir cut + nightvision=1

**Comment by dmolner** [comment] 2017-12-19 09:08
@EliasKotlyar 
Work perfect IR ON + IR cut ON + nightvison=1 for dark.
IR OFF + IR cut OFF + nightvison=0 for day

**Comment by EliasKotlyar** [comment] 2017-12-21 11:38
Okey i think this issue is resolved. I will close it.

**Closed by EliasKotlyar** 2017-12-21 11:38 UTC

**Comment by pplucky** [comment] 2018-01-09 23:37
Hello.

The greyscale is only valid for picture capturing or can it be also for RTSP?
I think original firmware does it.

Now I can only have the violet image on RTSP.

Thanks in advance.

**Comment by UmerFraz** [comment] 2018-03-04 21:14
Hi, for some reason i am now getting the purple picture. Before i updated to latest FW (not sure if one was updated anyways within a matter of 3/4 days) night-vision was working fine.

I have tried all controls and realised that IR-CUT is probably not working. so i have to turn off auto night vision and turn on the IR LED to get atleast the purple stream.

If i keep auto-nightvision on  and try to turn on IR CUT then i hear a click and then another click immediately after as if it is being reset by auto night vision. with auto night vision off this doesnt happen. 

also wether the ir cut is on or off it doesnt make a difference.

another problem is the worse quality of purple image.

any help will be highly appreciated.

**Comment by avalonis1** [comment] 2018-03-08 17:59
Hello,

First thank for your firmware and sorry for my english.

I try to use this camera with tinycam pro but I have a problem with the auto night vision if I want use this function I have to use "On IR LED" and "On IR CUT", for information if in manage scrip, I active night auto detection, the camera turns off automaticaly the IR LED and CUT.

For the grey color, I can have it only when I activate "RTSP-Server Nightvision".

I hope you will be able to find solution for auto night vision, besause your firmware is very cool .

Thanks
Regards
Avalonis

**Comment by thisisjerk** [comment] 2019-02-09 10:23
Is it possible to turn the night vision on persistently while the IR LED is OFF?
